insert into additional_charges (id, description, amount, order_id) values (1, 'Mauris sit amet eros.', 3, 129);
insert into additional_charges (id, description, amount, order_id) values (2, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 10, 5);
insert into additional_charges (id, description, amount, order_id) values (3, null, 10, 18);
insert into additional_charges (id, description, amount, order_id) values (4, null, 6, 124);
insert into additional_charges (id, description, amount, order_id) values (5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1, 60);
insert into additional_charges (id, description, amount, order_id) values (6, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 10, 55);
insert into additional_charges (id, description, amount, order_id) values (7, 'Mauris sit amet eros.', 8, 64);
insert into additional_charges (id, description, amount, order_id) values (8, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 5, 55);
insert into additional_charges (id, description, amount, order_id) values (9, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 10, 91);
insert into additional_charges (id, description, amount, order_id) values (10, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 3, 21);
insert into additional_charges (id, description, amount, order_id) values (11, 'Praesent blandit.', 10, 15);
insert into additional_charges (id, description, amount, order_id) values (12, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', 10, 25);
insert into additional_charges (id, description, amount, order_id) values (13, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 9, 55);
insert into additional_charges (id, description, amount, order_id) values (14, null, 2, 27);
insert into additional_charges (id, description, amount, order_id) values (15, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 4, 51);
insert into additional_charges (id, description, amount, order_id) values (16, 'Cras in purus eu magna vulputate luctus.', 10, 40);
insert into additional_charges (id, description, amount, order_id) values (17, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 9, 136);
insert into additional_charges (id, description, amount, order_id) values (18, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 3, 29);
insert into additional_charges (id, description, amount, order_id) values (19, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 8, 135);
insert into additional_charges (id, description, amount, order_id) values (20, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 6, 18);
insert into additional_charges (id, description, amount, order_id) values (21, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', 3, 150);
insert into additional_charges (id, description, amount, order_id) values (22, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 9, 84);
insert into additional_charges (id, description, amount, order_id) values (23, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 4, 70);
insert into additional_charges (id, description, amount, order_id) values (24, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 4, 2);
insert into additional_charges (id, description, amount, order_id) values (25, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 10, 67);
insert into additional_charges (id, description, amount, order_id) values (26, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 0, 17);
insert into additional_charges (id, description, amount, order_id) values (27, 'Integer a nibh.', 1, 53);
insert into additional_charges (id, description, amount, order_id) values (28, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 3, 48);
insert into additional_charges (id, description, amount, order_id) values (29, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 5, 55);
insert into additional_charges (id, description, amount, order_id) values (30, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 10, 62);
insert into additional_charges (id, description, amount, order_id) values (31, 'In congue. Etiam justo. Etiam pretium iaculis justo.', 5, 97);
insert into additional_charges (id, description, amount, order_id) values (32, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 8, 100);
insert into additional_charges (id, description, amount, order_id) values (33, null, 7, 57);
insert into additional_charges (id, description, amount, order_id) values (34, 'Phasellus sit amet erat.', 7, 119);
insert into additional_charges (id, description, amount, order_id) values (35, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 0, 117);
insert into additional_charges (id, description, amount, order_id) values (36, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 5, 99);
insert into additional_charges (id, description, amount, order_id) values (37, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 3, 56);
insert into additional_charges (id, description, amount, order_id) values (38, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 3, 108);
insert into additional_charges (id, description, amount, order_id) values (39, 'Proin risus.', 9, 21);
insert into additional_charges (id, description, amount, order_id) values (40, 'Nulla nisl. Nunc nisl.', 4, 143);
insert into additional_charges (id, description, amount, order_id) values (41, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 4, 65);
insert into additional_charges (id, description, amount, order_id) values (42, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 0, 148);
insert into additional_charges (id, description, amount, order_id) values (43, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1, 52);
insert into additional_charges (id, description, amount, order_id) values (44, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 8, 54);
insert into additional_charges (id, description, amount, order_id) values (45, null, 6, 37);
insert into additional_charges (id, description, amount, order_id) values (46, 'Nunc rhoncus dui vel sem. Sed sagittis.', 2, 45);
insert into additional_charges (id, description, amount, order_id) values (47, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 1, 33);
insert into additional_charges (id, description, amount, order_id) values (48, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 6, 36);
insert into additional_charges (id, description, amount, order_id) values (49, 'Fusce consequat.', 7, 4);
insert into additional_charges (id, description, amount, order_id) values (50, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 0, 138);
insert into additional_charges (id, description, amount, order_id) values (51, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 6, 79);
insert into additional_charges (id, description, amount, order_id) values (52, null, 1, 102);
insert into additional_charges (id, description, amount, order_id) values (53, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 5, 86);
insert into additional_charges (id, description, amount, order_id) values (54, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 8, 25);
insert into additional_charges (id, description, amount, order_id) values (55, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 7, 98);
insert into additional_charges (id, description, amount, order_id) values (56, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 5, 78);
insert into additional_charges (id, description, amount, order_id) values (57, null, 5, 114);
insert into additional_charges (id, description, amount, order_id) values (58, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 8, 54);
insert into additional_charges (id, description, amount, order_id) values (59, 'Suspendisse potenti. Nullam porttitor lacus at turpis.', 0, 127);
insert into additional_charges (id, description, amount, order_id) values (60, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 8, 40);
insert into additional_charges (id, description, amount, order_id) values (61, 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', 6, 78);
insert into additional_charges (id, description, amount, order_id) values (62, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 5, 141);
insert into additional_charges (id, description, amount, order_id) values (63, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 0, 3);
insert into additional_charges (id, description, amount, order_id) values (64, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 6, 106);
insert into additional_charges (id, description, amount, order_id) values (65, 'In eleifend quam a odio.', 7, 64);
insert into additional_charges (id, description, amount, order_id) values (66, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 6, 58);
insert into additional_charges (id, description, amount, order_id) values (67, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 27);
insert into additional_charges (id, description, amount, order_id) values (68, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 5, 111);
insert into additional_charges (id, description, amount, order_id) values (69, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 0, 66);
insert into additional_charges (id, description, amount, order_id) values (70, 'In hac habitasse platea dictumst.', 8, 116);
insert into additional_charges (id, description, amount, order_id) values (71, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 10, 28);
insert into additional_charges (id, description, amount, order_id) values (72, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, 80);
insert into additional_charges (id, description, amount, order_id) values (73, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 6, 2);
insert into additional_charges (id, description, amount, order_id) values (74, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 3, 98);
insert into additional_charges (id, description, amount, order_id) values (75, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, 44);
insert into additional_charges (id, description, amount, order_id) values (76, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 8, 133);
insert into additional_charges (id, description, amount, order_id) values (77, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 0, 90);
insert into additional_charges (id, description, amount, order_id) values (78, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, 78);
insert into additional_charges (id, description, amount, order_id) values (79, 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 4, 49);
insert into additional_charges (id, description, amount, order_id) values (80, 'Pellentesque eget nunc.', 0, 75);
insert into additional_charges (id, description, amount, order_id) values (81, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 9, 41);
insert into additional_charges (id, description, amount, order_id) values (82, null, 2, 74);
insert into additional_charges (id, description, amount, order_id) values (83, 'Integer a nibh.', 2, 115);
insert into additional_charges (id, description, amount, order_id) values (84, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, 18);
insert into additional_charges (id, description, amount, order_id) values (85, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 8, 91);
insert into additional_charges (id, description, amount, order_id) values (86, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 9, 11);
insert into additional_charges (id, description, amount, order_id) values (87, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 10, 91);
insert into additional_charges (id, description, amount, order_id) values (88, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 2, 25);
insert into additional_charges (id, description, amount, order_id) values (89, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 8, 26);
insert into additional_charges (id, description, amount, order_id) values (90, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 0, 54);
insert into additional_charges (id, description, amount, order_id) values (91, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 1, 62);
insert into additional_charges (id, description, amount, order_id) values (92, 'Integer a nibh. In quis justo.', 6, 17);
insert into additional_charges (id, description, amount, order_id) values (93, 'Sed ante. Vivamus tortor.', 8, 35);
insert into additional_charges (id, description, amount, order_id) values (94, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 10, 80);
insert into additional_charges (id, description, amount, order_id) values (95, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 2, 143);
insert into additional_charges (id, description, amount, order_id) values (96, 'Aliquam erat volutpat.', 0, 44);
insert into additional_charges (id, description, amount, order_id) values (97, null, 0, 68);
insert into additional_charges (id, description, amount, order_id) values (98, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 3, 133);
insert into additional_charges (id, description, amount, order_id) values (99, 'Etiam faucibus cursus urna.', 4, 54);
insert into additional_charges (id, description, amount, order_id) values (100, 'Nulla nisl.', 6, 49);
insert into additional_charges (id, description, amount, order_id) values (101, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, 8);
insert into additional_charges (id, description, amount, order_id) values (102, 'Quisque porta volutpat erat.', 5, 66);
insert into additional_charges (id, description, amount, order_id) values (103, 'Suspendisse potenti. In eleifend quam a odio.', 4, 3);
insert into additional_charges (id, description, amount, order_id) values (104, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 10, 19);
insert into additional_charges (id, description, amount, order_id) values (105, 'Phasellus sit amet erat. Nulla tempus.', 2, 18);
insert into additional_charges (id, description, amount, order_id) values (106, null, 10, 125);
insert into additional_charges (id, description, amount, order_id) values (107, null, 10, 149);
insert into additional_charges (id, description, amount, order_id) values (108, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', 1, 96);
insert into additional_charges (id, description, amount, order_id) values (109, 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 3, 63);
insert into additional_charges (id, description, amount, order_id) values (110, 'Suspendisse potenti. In eleifend quam a odio.', 8, 62);
insert into additional_charges (id, description, amount, order_id) values (111, null, 5, 100);
insert into additional_charges (id, description, amount, order_id) values (112, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 10, 16);
insert into additional_charges (id, description, amount, order_id) values (113, null, 7, 146);
insert into additional_charges (id, description, amount, order_id) values (114, 'Morbi quis tortor id nulla ultrices aliquet.', 10, 6);
insert into additional_charges (id, description, amount, order_id) values (115, 'Nulla nisl.', 8, 49);
insert into additional_charges (id, description, amount, order_id) values (116, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 8, 113);
insert into additional_charges (id, description, amount, order_id) values (117, 'Integer non velit.', 8, 77);
insert into additional_charges (id, description, amount, order_id) values (118, null, 1, 42);
insert into additional_charges (id, description, amount, order_id) values (119, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 8, 43);
insert into additional_charges (id, description, amount, order_id) values (120, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 1, 146);
insert into additional_charges (id, description, amount, order_id) values (121, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 5, 148);
insert into additional_charges (id, description, amount, order_id) values (122, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1, 15);
insert into additional_charges (id, description, amount, order_id) values (123, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 6, 96);
insert into additional_charges (id, description, amount, order_id) values (124, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 9, 93);
insert into additional_charges (id, description, amount, order_id) values (125, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 5, 48);
insert into additional_charges (id, description, amount, order_id) values (126, 'Nulla tellus.', 7, 67);
insert into additional_charges (id, description, amount, order_id) values (127, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 9, 37);
insert into additional_charges (id, description, amount, order_id) values (128, 'Pellentesque at nulla. Suspendisse potenti.', 8, 129);
insert into additional_charges (id, description, amount, order_id) values (129, null, 1, 63);
insert into additional_charges (id, description, amount, order_id) values (130, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, 131);
insert into additional_charges (id, description, amount, order_id) values (131, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 10, 34);
insert into additional_charges (id, description, amount, order_id) values (132, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 2, 46);
insert into additional_charges (id, description, amount, order_id) values (133, 'Morbi vel lectus in quam fringilla rhoncus.', 1, 44);
insert into additional_charges (id, description, amount, order_id) values (134, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 2, 146);
insert into additional_charges (id, description, amount, order_id) values (135, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 3, 70);
insert into additional_charges (id, description, amount, order_id) values (136, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 0, 83);
insert into additional_charges (id, description, amount, order_id) values (137, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 5, 148);
insert into additional_charges (id, description, amount, order_id) values (138, 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, 89);
insert into additional_charges (id, description, amount, order_id) values (139, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 6, 16);
insert into additional_charges (id, description, amount, order_id) values (140, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 4, 7);
insert into additional_charges (id, description, amount, order_id) values (141, null, 8, 122);
insert into additional_charges (id, description, amount, order_id) values (142, 'Cras in purus eu magna vulputate luctus.', 6, 41);
insert into additional_charges (id, description, amount, order_id) values (143, 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 0, 100);
insert into additional_charges (id, description, amount, order_id) values (144, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 4, 97);
insert into additional_charges (id, description, amount, order_id) values (145, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 0, 112);
insert into additional_charges (id, description, amount, order_id) values (146, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 2, 146);
insert into additional_charges (id, description, amount, order_id) values (147, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0, 121);
insert into additional_charges (id, description, amount, order_id) values (148, null, 3, 67);
insert into additional_charges (id, description, amount, order_id) values (149, 'Morbi quis tortor id nulla ultrices aliquet.', 6, 89);
insert into additional_charges (id, description, amount, order_id) values (150, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 8, 64);
