insert into products (id, name, description, price, stock) values (1, 'Wine - Muscadet Sur Lie', 'Revision of Drain Dev in Scrotum & Tunica, Open Approach', 282328, 39);
insert into products (id, name, description, price, stock) values (2, 'Cilantro / Coriander - Fresh', 'Restrict R Int Carotid w Extralum Dev, Perc Endo', 925023, 132);
insert into products (id, name, description, price, stock) values (3, 'Appetizer - Asian Shrimp Roll', 'Removal of Radioactive Element from Tracheobronc Tree, Endo', 938650, 91);
insert into products (id, name, description, price, stock) values (4, 'Table Cloth 81x81 Colour', 'Insertion of Monitoring Device into Liver, Open Approach', 315778, 183);
insert into products (id, name, description, price, stock) values (5, 'Lamb - Whole Head Off,nz', 'Introduction of Anti-inflammatory into Bil/Panc Tract, Endo', 238964, 422);
insert into products (id, name, description, price, stock) values (6, 'Baking Soda', 'Removal of Int Fix from L Thumb Phalanx, Extern Approach', 290160, 9);
insert into products (id, name, description, price, stock) values (7, 'Foam Dinner Plate', 'Bypass Left Fallopian Tube to L Fallop, Perc Endo Approach', 349286, 316);
insert into products (id, name, description, price, stock) values (8, 'Ecolab - Mikroklene 4/4 L', 'Reposition Coccygeal Joint with Int Fix, Perc Endo Approach', 840629, 10);
insert into products (id, name, description, price, stock) values (9, 'Savory', 'Reposition Left Radius with Hybrid Ext Fix, Open Approach', 8397, 324);
insert into products (id, name, description, price, stock) values (10, 'Syrup - Chocolate', 'Insert Radioact Elem in L Low Extrem, Perc Endo', 646585, 27);
insert into products (id, name, description, price, stock) values (11, 'Kale - Red', 'Removal of Infusion Device from R Low Extrem, Open Approach', 872999, 329);
insert into products (id, name, description, price, stock) values (12, 'Gelatine Powder', 'Release Left Lobe Liver, Percutaneous Endoscopic Approach', 176089, 360);
insert into products (id, name, description, price, stock) values (13, 'Pie Filling - Pumpkin', 'CT Scan of Bi Temporomand Jt using L Osm Contrast', 341171, 172);
insert into products (id, name, description, price, stock) values (14, 'Oven Mitts 17 Inch', 'Introduce Oth Antineoplastic in Central Art, Open', 254580, 24);
insert into products (id, name, description, price, stock) values (15, 'Beef - Cow Feet Split', 'Replacement of Colic Vein with Autol Sub, Open Approach', 864539, 53);
insert into products (id, name, description, price, stock) values (16, 'Bagelers - Cinn / Brown Sugar', 'Division of Right Maxilla, Percutaneous Approach', 948298, 133);
insert into products (id, name, description, price, stock) values (17, 'Guava', 'Replacement of Nasopharynx with Autol Sub, Open Approach', 298596, 369);
insert into products (id, name, description, price, stock) values (18, 'Beer - Blue', 'Supplement Perineum Subcu/Fascia w Autol Sub, Perc', 871404, 351);
insert into products (id, name, description, price, stock) values (19, 'Appetizer - Mango Chevre', 'Introduce of Analg/Hypnot/Sedat into Low GI, Perc Approach', 68021, 188);
insert into products (id, name, description, price, stock) values (20, 'Pepper - Red Thai', 'Revision of Drain Dev in Up Intest Tract, Perc Approach', 243475, 424);
insert into products (id, name, description, price, stock) values (21, 'Vodka - Smirnoff', 'Fluoroscopy of Other Upper Arteries', 11052, 421);
insert into products (id, name, description, price, stock) values (22, 'Dikon', 'Bypass R Temporal Art to Intracran Art w Autol Vn, Open', 551624, 83);
insert into products (id, name, description, price, stock) values (23, 'Lobster - Live', 'Replace of R Hip Tendon with Nonaut Sub, Perc Endo Approach', 310128, 459);
insert into products (id, name, description, price, stock) values (24, 'Banana', 'Removal of Int Fix from L Carpal Jt, Perc Endo Approach', 798468, 276);
insert into products (id, name, description, price, stock) values (25, 'Pastry - Apple Muffins - Mini', 'Supplement Upper Artery with Autol Sub, Perc Approach', 492393, 425);
insert into products (id, name, description, price, stock) values (26, 'Rhubarb', 'Magnetic Resonance Imaging (MRI) of Right Lower Leg', 989400, 146);
insert into products (id, name, description, price, stock) values (27, 'Oil - Truffle, Black', 'Supplement L Ext Carotid with Nonaut Sub, Open Approach', 590504, 271);
insert into products (id, name, description, price, stock) values (28, 'Wine - Saint Emilion Calvet', 'Removal of Synth Sub from L Up Extrem, Perc Endo Approach', 967751, 68);
insert into products (id, name, description, price, stock) values (29, 'Chicken - Leg, Boneless', 'HDR Brachytherapy of Duodenum using Oth Isotope', 475116, 486);
insert into products (id, name, description, price, stock) values (30, 'Star Anise, Whole', 'Reposition Occip Jt with Int Fix, Extern Approach', 187571, 80);
insert into products (id, name, description, price, stock) values (31, 'Stock - Beef, White', 'LDR Brachytherapy of Hard Palate using Oth Isotope', 934847, 15);
insert into products (id, name, description, price, stock) values (32, 'Lamb - Sausage Casings', 'Restriction of R Int Mamm Art, Perc Endo Approach', 499574, 43);
insert into products (id, name, description, price, stock) values (33, 'Aspic - Light', 'Drainage of Greater Omentum, Perc Endo Approach, Diagn', 725654, 44);
insert into products (id, name, description, price, stock) values (34, 'Grenadine', 'Central Nervous System, Drainage', 771401, 98);
insert into products (id, name, description, price, stock) values (35, 'Wine - Pinot Noir Stoneleigh', 'Replace of R Subclav Vein with Autol Sub, Perc Endo Approach', 223846, 64);
insert into products (id, name, description, price, stock) values (36, 'Wine - German Riesling', 'Insert of Pressure Sens into Thor Aorta Desc, Perc Approach', 399121, 11);
insert into products (id, name, description, price, stock) values (37, 'Rosemary - Primerba, Paste', 'Revision of Autol Sub in Omentum, Perc Endo Approach', 472288, 2);
insert into products (id, name, description, price, stock) values (38, 'Creme De Banane - Marie', 'Replace L Up Arm Subcu/Fascia w Nonaut Sub, Open', 654667, 14);
insert into products (id, name, description, price, stock) values (39, 'Soup - Campbells, Creamy', 'Bypass Mid Esophag to Jejunum with Nonaut Sub, Open Approach', 835325, 484);
insert into products (id, name, description, price, stock) values (40, 'French Pastries', 'Repair Cystic Duct, Via Natural or Artificial Opening', 67002, 188);
insert into products (id, name, description, price, stock) values (41, 'Beef - Cow Feet Split', 'Introduce Oth Anti-infect in Epidural Space, Perc', 979622, 178);
insert into products (id, name, description, price, stock) values (42, 'Pants Custom Dry Clean', 'Insertion of Hybrid Ext Fix into R Ulna, Perc Approach', 470173, 202);
insert into products (id, name, description, price, stock) values (43, 'Squash - Sunburst', 'Transplantation of GI Sys into POC, Via Opening', 913591, 201);
insert into products (id, name, description, price, stock) values (44, 'Wine - Blue Nun Qualitatswein', 'Removal of Synth Sub from Heart, Perc Endo Approach', 188419, 253);
insert into products (id, name, description, price, stock) values (45, 'Langers - Mango Nectar', 'Fluoroscopy of Ileal Diversion Loop using H Osm Contrast', 264288, 113);
insert into products (id, name, description, price, stock) values (46, 'Sauce - Ranch Dressing', 'Revise of Infusion Dev in R Toe Phalanx Jt, Extern Approach', 345902, 371);
insert into products (id, name, description, price, stock) values (47, 'Wine La Vielle Ferme Cote Du', 'Alteration of Right Upper Arm with Synth Sub, Open Approach', 479744, 325);
insert into products (id, name, description, price, stock) values (48, 'Clams - Canned', 'Fusion of Right Shoulder Joint with Synth Sub, Open Approach', 361032, 197);
insert into products (id, name, description, price, stock) values (49, 'Chives - Fresh', 'Occlusion R Int Carotid w Bioact Intralum, Open', 397556, 153);
insert into products (id, name, description, price, stock) values (50, 'Wine - Ruffino Chianti Classico', 'Replacement of Right Cornea with Nonaut Sub, Extern Approach', 635881, 322);
insert into products (id, name, description, price, stock) values (51, 'Bagels Poppyseed', 'Dilate of 3 Cor Art with Drug-elut Intra, Perc Endo Approach', 217117, 154);
insert into products (id, name, description, price, stock) values (52, 'Milk - 1%', 'Extirpation of Matter from L Low Leg Tendon, Perc Approach', 296156, 193);
insert into products (id, name, description, price, stock) values (53, 'Wine - George Duboeuf Rose', 'Extirpation of Matter from Radial Nerve, Perc Endo Approach', 433766, 373);
insert into products (id, name, description, price, stock) values (54, 'Tea Peppermint', 'Extraction of L Foot Subcu/Fascia, Open Approach', 551456, 20);
insert into products (id, name, description, price, stock) values (55, 'Pie Shell - 5', 'Drainage of Left Diaphragm, Percutaneous Approach, Diagn', 113849, 432);
insert into products (id, name, description, price, stock) values (56, 'Veal Inside - Provimi', 'Excision of Lumbar Vertebra, Percutaneous Approach, Diagn', 566119, 476);
insert into products (id, name, description, price, stock) values (57, 'Sauce - Salsa', 'Drainage of Left Ankle Tendon, Perc Endo Approach, Diagn', 672558, 330);
insert into products (id, name, description, price, stock) values (58, 'Wine - Red, Gamay Noir', 'Supplement Bilateral Breast with Autol Sub, Open Approach', 332992, 10);
insert into products (id, name, description, price, stock) values (59, 'Pepper - Chipotle, Canned', 'Replacement of Right Inner Ear with Autol Sub, Open Approach', 752619, 219);
insert into products (id, name, description, price, stock) values (60, 'Sugar - Splenda Sweetener', 'Drainage of Left Common Carotid Artery, Perc Approach', 872554, 493);
insert into products (id, name, description, price, stock) values (61, 'Pasta - Penne, Rigate, Dry', 'Excision of Lower Vein, Percutaneous Approach, Diagnostic', 892130, 292);
insert into products (id, name, description, price, stock) values (62, 'Cheese - Gouda', 'Coord/Dexterity Trmt Neuro Up Back/UE w Prosthesis', 141049, 105);
insert into products (id, name, description, price, stock) values (63, 'Persimmons', 'Dilate L Ulnar Art, Bifurc, w 4+ Intralum Dev, Perc', 240632, 244);
insert into products (id, name, description, price, stock) values (64, 'Appetizer - Assorted Box', 'Bypass Innom Art to R Low Arm Art w Nonaut Sub, Open', 941775, 486);
insert into products (id, name, description, price, stock) values (65, 'Basil - Thai', 'Fluoroscopy of Right Renal Vein using Oth Contrast, Guidance', 390694, 377);
insert into products (id, name, description, price, stock) values (66, 'Wine - Red, Pelee Island Merlot', 'Release Left Knee Tendon, Open Approach', 618001, 123);
insert into products (id, name, description, price, stock) values (67, 'Potatoes - Parissienne', 'Supplement Female Perineum with Synth Sub, Open Approach', 926468, 400);
insert into products (id, name, description, price, stock) values (68, 'Chicken - Leg, Boneless', 'Excision of Right Ulna, Open Approach, Diagnostic', 380490, 316);
insert into products (id, name, description, price, stock) values (69, 'Syrup - Chocolate', 'Replacement of R Temporal Art with Nonaut Sub, Open Approach', 956181, 76);
insert into products (id, name, description, price, stock) values (70, 'Shrimp - 150 - 250', 'Occlusion of Gastric Vein with Extralum Dev, Open Approach', 67990, 436);
insert into products (id, name, description, price, stock) values (71, 'Rye Special Old', 'Drainage of Left Posterior Tibial Artery, Open Approach', 624692, 100);
insert into products (id, name, description, price, stock) values (72, 'Egg - Salad Premix', 'Fluoroscopy Cereb & Cerebel Vein w Oth Contrast, Guidance', 432605, 443);
insert into products (id, name, description, price, stock) values (73, 'Glaze - Apricot', 'Revision of Synth Sub in R Metatarsal, Open Approach', 482783, 226);
insert into products (id, name, description, price, stock) values (74, 'Cabbage - Savoy', 'Excision of Right Kidney Pelvis, Perc Approach, Diagn', 141582, 285);
insert into products (id, name, description, price, stock) values (75, 'Cheese - Cheddar, Medium', 'Removal of Synthetic Substitute from Bladder, Perc Approach', 963516, 402);
insert into products (id, name, description, price, stock) values (76, 'Cheese - Victor Et Berthold', 'Bypass R Kidney Pelvis to Ileocutan w Synth Sub, Open', 426766, 203);
insert into products (id, name, description, price, stock) values (77, 'Lamb - Loin, Trimmed, Boneless', 'Alteration of L Wrist with Nonaut Sub, Open Approach', 410096, 157);
insert into products (id, name, description, price, stock) values (78, 'Seedlings - Buckwheat, Organic', 'Supplement Left Ventricle with Zooplastic, Perc Approach', 660915, 147);
insert into products (id, name, description, price, stock) values (79, 'Pork - Sausage, Medium', 'Bypass L Great Saphenous to Low Vein w Synth Sub, Perc Endo', 79695, 126);
insert into products (id, name, description, price, stock) values (80, 'Cinnamon - Stick', 'Reposition Right Subclavian Vein, Perc Endo Approach', 921065, 296);
insert into products (id, name, description, price, stock) values (81, 'Cups 10oz Trans', 'Drainage of Right Middle Lobe Bronchus, Endo, Diagn', 663629, 382);
insert into products (id, name, description, price, stock) values (82, 'Wine - Remy Pannier Rose', 'Alter of Fem Perineum with Nonaut Sub, Perc Endo Approach', 713540, 252);
insert into products (id, name, description, price, stock) values (83, 'Cheese - Comtomme', 'Revision of Nonaut Sub in R Tarsal Jt, Perc Endo Approach', 322658, 278);
insert into products (id, name, description, price, stock) values (84, 'Pur Source', 'Supplement Left Wrist Region with Autol Sub, Open Approach', 177297, 353);
insert into products (id, name, description, price, stock) values (85, 'Sugar - Brown, Individual', 'Reposition Celiac Artery, Percutaneous Approach', 137528, 90);
insert into products (id, name, description, price, stock) values (86, 'Coffee - Flavoured', 'Removal of Other Device from Face, External Approach', 383944, 479);
insert into products (id, name, description, price, stock) values (87, 'Container - Foam Dixie 12 Oz', 'Resection of Tonsils, Open Approach', 946783, 150);
insert into products (id, name, description, price, stock) values (88, 'Doilies - 12, Paper', 'Transfer R Neck Muscle with Skin, Subcu, Perc Endo Approach', 949336, 243);
insert into products (id, name, description, price, stock) values (89, 'Syrup - Monin, Irish Cream', 'MRI of L Kidney using Oth Contrast', 662957, 362);
insert into products (id, name, description, price, stock) values (90, 'Cheese Cheddar Processed', 'Occlusion of L Sperm Cord with Extralum Dev, Open Approach', 963114, 231);
insert into products (id, name, description, price, stock) values (91, 'Cumin - Whole', 'Extirpation of Matter from L Great Saphenous, Perc Approach', 905005, 426);
insert into products (id, name, description, price, stock) values (92, 'Beer - Labatt Blue', 'Revision of Nonaut Sub in L Humeral Head, Perc Approach', 132987, 488);
insert into products (id, name, description, price, stock) values (93, 'Oven Mitts 17 Inch', 'Fragmentation in Left Lower Lobe Bronchus, External Approach', 332740, 43);
insert into products (id, name, description, price, stock) values (94, 'Champagne - Brights, Dry', 'Drainage of Left Face Vein, Perc Endo Approach, Diagn', 7778, 300);
insert into products (id, name, description, price, stock) values (95, 'Fish - Halibut, Cold Smoked', 'Drainage of L Low Arm & Wrist Muscle, Perc Endo Approach', 135142, 498);
insert into products (id, name, description, price, stock) values (96, 'Soap - Mr.clean Floor Soap', 'Removal of Nonaut Sub from Urethra, Endo', 514339, 360);
insert into products (id, name, description, price, stock) values (97, 'Soup - Cream Of Broccoli, Dry', 'Bypass R Ext Iliac Art to R Int Ilia w Autol Vn, Open', 206632, 55);
insert into products (id, name, description, price, stock) values (98, 'Flower - Commercial Bronze', 'Revision of Drainage Device in R Shoulder Jt, Open Approach', 516777, 381);
insert into products (id, name, description, price, stock) values (99, 'Emulsifier', 'Dilate R Subclav Art, Bifurc, w 4+ Intralum Dev, Open', 871645, 171);
insert into products (id, name, description, price, stock) values (100, 'Yogurt - Banana, 175 Gr', 'Removal of Drain Dev from L Sacroiliac Jt, Open Approach', 481905, 451);
insert into products (id, name, description, price, stock) values (101, 'Noodles - Steamed Chow Mein', 'Dilation of Sup Mesent Art with 2 Drug-elut, Open Approach', 27171, 187);
insert into products (id, name, description, price, stock) values (102, 'Fenngreek Seed', 'Excision of Left Fibula, Perc Endo Approach, Diagn', 567555, 144);
insert into products (id, name, description, price, stock) values (103, 'Yucca', 'Revision of Int Fix in L Toe Phalanx, Perc Approach', 358974, 239);
insert into products (id, name, description, price, stock) values (104, 'Napkin - Beverge, White 2 - Ply', 'Revision of Synthetic Substitute in C-thor Jt, Open Approach', 341715, 56);
insert into products (id, name, description, price, stock) values (105, 'Soup Bowl Clear 8oz92008', 'Dilation of L Pulm Art with Intralum Dev, Open Approach', 523356, 358);
insert into products (id, name, description, price, stock) values (106, 'Cleaner - Bleach', 'Drainage of Right Knee Joint, Open Approach, Diagnostic', 759371, 391);
insert into products (id, name, description, price, stock) values (107, 'Sauce - Mint', 'Revision of Nonaut Sub in Small Intest, Perc Endo Approach', 374193, 444);
insert into products (id, name, description, price, stock) values (108, 'Rice - 7 Grain Blend', 'Replace R Com Iliac Vein w Autol Sub, Perc Endo', 799526, 26);
insert into products (id, name, description, price, stock) values (109, 'Bread - Olive', 'Immobilization of Left Upper Extremity using Splint', 372062, 82);
insert into products (id, name, description, price, stock) values (110, 'Pie Box - Cello Window 2.5', 'Reattachment of Left Abdomen Tendon, Perc Endo Approach', 858903, 76);
insert into products (id, name, description, price, stock) values (111, 'Chinese Lemon Pork', 'Wound Mgmt Treatment of Integu Up Back/UE using Orthosis', 904385, 221);
insert into products (id, name, description, price, stock) values (112, 'Soup - French Onion, Dry', 'Release Right Mastoid Sinus, Perc Endo Approach', 375766, 445);
insert into products (id, name, description, price, stock) values (113, 'Pasta - Canelloni', 'Extraction of Right Lower Leg Skin, External Approach', 843085, 377);
insert into products (id, name, description, price, stock) values (114, 'Curry Paste - Green Masala', 'Destruction of Left Large Intestine, Percutaneous Approach', 329961, 198);
insert into products (id, name, description, price, stock) values (115, 'Potatoes - Yukon Gold 5 Oz', 'Removal of Cardiac Lead from Heart, Percutaneous Approach', 398929, 288);
insert into products (id, name, description, price, stock) values (116, 'Snapple Raspberry Tea', 'Release R Low Extrem Bursa/Lig, Perc Endo Approach', 96004, 162);
insert into products (id, name, description, price, stock) values (117, 'Wine - Red, Antinori Santa', 'Division of Left Sphenoid Bone, Percutaneous Approach', 959917, 215);
insert into products (id, name, description, price, stock) values (118, 'Squid U5 - Thailand', 'MRI of Bi Pulm Vein using Oth Contrast', 875998, 225);
insert into products (id, name, description, price, stock) values (119, 'Wine - Champagne Brut Veuve', 'Resection of Left Metatarsal-Phalangeal Joint, Open Approach', 947092, 315);
insert into products (id, name, description, price, stock) values (120, 'Lotus Rootlets - Canned', 'Occlusion L Ext Iliac Vein w Intralum Dev, Open', 918548, 98);
insert into products (id, name, description, price, stock) values (121, 'Mikes Hard Lemonade', 'Revision of Intralum Dev in Up Art, Perc Endo Approach', 949437, 444);
insert into products (id, name, description, price, stock) values (122, 'Wine - Two Oceans Sauvignon', 'Replacement of R Thyroid Art with Autol Sub, Open Approach', 395556, 34);
insert into products (id, name, description, price, stock) values (123, 'Okra', 'Release Right Pulmonary Artery, Percutaneous Approach', 885278, 170);
insert into products (id, name, description, price, stock) values (124, 'Beer - Muskoka Cream Ale', 'Release Right Clavicle, Open Approach', 322154, 313);
insert into products (id, name, description, price, stock) values (125, 'Pomello', 'Bypass L Popl Art to Low Ex Art w Synth Sub, Open', 934851, 235);
insert into products (id, name, description, price, stock) values (126, 'Pork - Sausage, Medium', 'Drainage of L Low Leg Subcu/Fascia, Perc Approach', 904444, 439);
insert into products (id, name, description, price, stock) values (127, 'Molasses - Fancy', 'Replacement of L Carpal Jt with Nonaut Sub, Open Approach', 617220, 494);
insert into products (id, name, description, price, stock) values (128, 'Nutmeg - Ground', 'Irrigation of Upper GI using Irrigat, Via Opening, Diagn', 693741, 116);
insert into products (id, name, description, price, stock) values (129, 'Sparkling Wine - Rose, Freixenet', 'Introduction of Oth Hormone into Periph Vein, Open Approach', 999958, 357);
insert into products (id, name, description, price, stock) values (130, 'Tomato - Green', 'Dilate L Thyroid Art, Bifurc, w 4 Drug-elut, Perc Endo', 781198, 151);
insert into products (id, name, description, price, stock) values (131, 'Bar Bran Honey Nut', 'Revision of Synth Sub in Diaphragm, Extern Approach', 573525, 130);
insert into products (id, name, description, price, stock) values (132, 'Anchovy Paste - 56 G Tube', 'Revision of Drain Dev in R Sternoclav Jt, Open Approach', 631788, 411);
insert into products (id, name, description, price, stock) values (133, 'V8 Splash Strawberry Banana', 'Dilate L Com Iliac Art w 2 Drug-elut, Perc Endo', 974223, 285);
insert into products (id, name, description, price, stock) values (134, 'Lamb - Whole, Frozen', 'Revision of Radioactive Element in Lower Jaw, Perc Approach', 924710, 160);
insert into products (id, name, description, price, stock) values (135, 'Figs', 'Excision of Lumbar Spinal Cord, Percutaneous Approach', 92404, 466);
insert into products (id, name, description, price, stock) values (136, 'Everfresh Products', 'Reposition Sciatic Nerve, Percutaneous Endoscopic Approach', 649800, 136);
insert into products (id, name, description, price, stock) values (137, 'Jam - Marmalade, Orange', 'Drainage of Right Shoulder Region, Percutaneous Approach', 291720, 159);
insert into products (id, name, description, price, stock) values (138, 'Syrup - Monin, Irish Cream', 'Removal of Synth Sub from R Up Femur, Perc Approach', 508041, 412);
insert into products (id, name, description, price, stock) values (139, 'Yoplait Drink', 'Inspection of Female Perineum, Perc Endo Approach', 273399, 109);
insert into products (id, name, description, price, stock) values (140, 'Saskatoon Berries - Frozen', 'Extirpation of Matter from Right Iris, Percutaneous Approach', 580567, 273);
insert into products (id, name, description, price, stock) values (141, 'Soap - Mr.clean Floor Soap', 'Destruction of Aortic Lymphatic, Perc Endo Approach', 296998, 426);
insert into products (id, name, description, price, stock) values (142, 'Oven Mitts - 15 Inch', 'Removal of Drain Dev from Up Bursa/Lig, Perc Endo Approach', 668009, 159);
insert into products (id, name, description, price, stock) values (143, 'Beef - Outside, Round', 'Occlusion of Bilateral Fallopian Tubes, Via Opening', 848001, 396);
insert into products (id, name, description, price, stock) values (144, 'Cookie Dough - Double', 'Replacement of Left Nipple with Autol Sub, Extern Approach', 560664, 318);
insert into products (id, name, description, price, stock) values (145, 'Bread - Crumbs, Bulk', 'Replacement of L Low Femur with Autol Sub, Perc Approach', 252089, 422);
insert into products (id, name, description, price, stock) values (146, 'Wine - Vouvray Cuvee Domaine', 'Revision of Nonaut Sub in L Shoulder Jt, Perc Approach', 963695, 301);
insert into products (id, name, description, price, stock) values (147, 'Cheese - Colby', 'Fusion of L Metacarpophal Jt with Synth Sub, Open Approach', 15535, 286);
insert into products (id, name, description, price, stock) values (148, 'Glass - Juice Clear 5oz 55005', 'Removal of Autol Sub from R Low Femur, Perc Endo Approach', 23345, 172);
insert into products (id, name, description, price, stock) values (149, 'Trueblue - Blueberry', 'Bypass R Com Iliac Art to B Int Ilia w Synth Sub, Open', 579423, 455);
insert into products (id, name, description, price, stock) values (150, 'Extract - Lemon', 'Removal of Drainage Device from Mediastinum, Perc Approach', 509513, 307);
insert into products (id, name, description, price, stock) values (151, 'Appetizer - Seafood Assortment', 'Replace of L Foot Subcu/Fascia with Synth Sub, Perc Approach', 836336, 445);
insert into products (id, name, description, price, stock) values (152, 'Cookies - Amaretto', 'Drainage of Right Thorax Muscle, Percutaneous Approach', 829688, 111);
insert into products (id, name, description, price, stock) values (153, 'Flour Dark Rye', 'Reattachment of Left Upper Leg Muscle, Open Approach', 928843, 331);
insert into products (id, name, description, price, stock) values (154, 'Pepsi, 355 Ml', 'Drainage of Left Tarsal, Open Approach', 331713, 36);
insert into products (id, name, description, price, stock) values (155, 'Fruit Salad Deluxe', 'Extirpate of Matter from R Up Leg Muscle, Perc Endo Approach', 354746, 170);
insert into products (id, name, description, price, stock) values (156, 'Dome Lid Clear P92008h', 'Removal of Monitor Dev from Tracheobronc Tree, Via Opening', 273047, 130);
insert into products (id, name, description, price, stock) values (157, 'Puree - Blackcurrant', 'Insertion of Feeding Dev into Duodenum, Perc Endo Approach', 731877, 490);
insert into products (id, name, description, price, stock) values (158, 'Pastry - Cheese Baked Scones', 'Dilation of L Lacrml Duct with Intralum Dev, Via Opening', 736095, 133);
insert into products (id, name, description, price, stock) values (159, 'Wine - Periguita Fonseca', 'Stereotactic Other Photon Radiosurgery of Diaphragm', 184972, 2);
insert into products (id, name, description, price, stock) values (160, 'Wine - Red Oakridge Merlot', 'Insertion of Infusion Dev into R Int Mamm Art, Open Approach', 769247, 345);
insert into products (id, name, description, price, stock) values (161, 'Bread - Mini Hamburger Bun', 'Excision of Gastric Vein, Percutaneous Approach', 834527, 35);
insert into products (id, name, description, price, stock) values (162, 'Glass Clear 7 Oz Xl', 'Drainage of Right Face Vein, Perc Endo Approach, Diagn', 735123, 310);
insert into products (id, name, description, price, stock) values (163, 'Lettuce - Boston Bib', 'Supplement Upper Gingiva with Nonaut Sub, Extern Approach', 299531, 455);
insert into products (id, name, description, price, stock) values (164, 'Lemonade - Mandarin, 591 Ml', 'Extirpation of Matter from R Adrenal Gland, Open Approach', 559657, 442);
insert into products (id, name, description, price, stock) values (165, 'Bread - Rosemary Focaccia', 'Occlusion of Anus with Intraluminal Device, Extern Approach', 891725, 121);
insert into products (id, name, description, price, stock) values (166, 'Truffle Shells - Semi - Sweet', 'Bypass L Popl Art to Peron Art with Autol Art, Open Approach', 985316, 274);
insert into products (id, name, description, price, stock) values (167, 'Sugar - Crumb', 'Extraction of Thoracic Nerve, Open Approach', 672100, 174);
insert into products (id, name, description, price, stock) values (168, 'Juice - Prune', 'Destruction of Prostate, Open Approach', 229436, 12);
insert into products (id, name, description, price, stock) values (169, 'Rambutan', 'Drainage of Right Hip Bursa and Ligament, Open Approach', 630275, 25);
insert into products (id, name, description, price, stock) values (170, 'Scallops 60/80 Iqf', 'Revision of Other Device in Lower Jaw, External Approach', 823735, 173);
insert into products (id, name, description, price, stock) values (171, 'Avocado', 'Destruction of Bladder, Percutaneous Endoscopic Approach', 89112, 351);
insert into products (id, name, description, price, stock) values (172, 'Brandy Cherry - Mcguinness', 'Drainage of Thor Jt with Drain Dev, Open Approach', 235270, 312);
insert into products (id, name, description, price, stock) values (173, 'Soup - Campbells Beef Strogonoff', 'Introduction of BMP into Bone, Perc Approach', 45932, 405);
insert into products (id, name, description, price, stock) values (174, 'Veal - Brisket, Provimi,bnls', 'Occlusion of Common Bile Duct, Endo', 500641, 97);
insert into products (id, name, description, price, stock) values (175, 'Soupcontfoam16oz 116con', 'Occlusion of Hepatic Vein with Extralum Dev, Open Approach', 410879, 194);
insert into products (id, name, description, price, stock) values (176, 'Chevril', 'Removal of Synth Sub from Cisterna Chyli, Perc Endo Approach', 326885, 69);
insert into products (id, name, description, price, stock) values (177, 'Roe - Flying Fish', 'Drainage of Left Tunica Vaginalis, Perc Endo Approach', 219726, 440);
insert into products (id, name, description, price, stock) values (178, 'Versatainer Nc - 888', 'Planar Nucl Med Imag of Spine using Oth Radionuclide', 674569, 66);
insert into products (id, name, description, price, stock) values (179, 'Lettuce Romaine Chopped', 'Supplement R Int Mamm Art with Synth Sub, Open Approach', 711984, 206);
insert into products (id, name, description, price, stock) values (180, 'Steam Pan - Half Size Deep', 'Destruction of Lingula Bronchus, Endo', 947474, 339);
insert into products (id, name, description, price, stock) values (181, 'Cheese - Bakers Cream Cheese', 'Drainage of Retroperitoneum with Drain Dev, Open Approach', 561786, 483);
insert into products (id, name, description, price, stock) values (182, 'Pie Filling - Cherry', 'Alteration of Neck with Synthetic Substitute, Open Approach', 141731, 1);
insert into products (id, name, description, price, stock) values (183, 'Marjoram - Dried, Rubbed', 'Dilate of Portal Vein with Intralum Dev, Perc Endo Approach', 273859, 203);
insert into products (id, name, description, price, stock) values (184, 'Broom - Push', 'Dilate L Int Iliac Art, Bifurc, w 3 Intralum Dev, Open', 734936, 371);
insert into products (id, name, description, price, stock) values (185, 'Horseradish Root', 'Division of Right Maxilla, Percutaneous Endoscopic Approach', 259672, 215);
insert into products (id, name, description, price, stock) values (186, 'Milk - 1%', 'Dilation of Larynx, Open Approach', 173292, 486);
insert into products (id, name, description, price, stock) values (187, 'Coffee Decaf Colombian', 'Excision of Left External Iliac Vein, Open Approach', 650126, 30);
insert into products (id, name, description, price, stock) values (188, 'Syrup - Monin - Blue Curacao', 'Release Innominate Artery, Open Approach', 410239, 186);
insert into products (id, name, description, price, stock) values (189, 'Lid Coffeecup 12oz D9542b', 'Revision of Autol Sub in L Metatarsal, Extern Approach', 387768, 37);
insert into products (id, name, description, price, stock) values (190, 'Wine - Duboeuf Beaujolais', 'Drainage of R Hand Bursa/Lig with Drain Dev, Open Approach', 863620, 476);
insert into products (id, name, description, price, stock) values (191, 'Pepper - Red Bell', 'Dilation of R Brach Art with 2 Intralum Dev, Perc Approach', 506362, 43);
insert into products (id, name, description, price, stock) values (192, 'Apple - Delicious, Golden', 'Drainage of Gastric Artery with Drain Dev, Perc Approach', 148344, 41);
insert into products (id, name, description, price, stock) values (193, 'Pastry - Choclate Baked', 'Reposition Left Metatarsal-Tarsal Joint, Perc Endo Approach', 557337, 379);
insert into products (id, name, description, price, stock) values (194, 'Mussels - Cultivated', 'Revision of Nonaut Sub in Lumsac Jt, Open Approach', 285960, 368);
insert into products (id, name, description, price, stock) values (195, 'Grapes - Black', 'Replacement of L Up Arm Skin with Synth Sub, Extern Approach', 544384, 43);
insert into products (id, name, description, price, stock) values (196, 'Milk - Condensed', 'Supplement L Index Finger with Autol Sub, Perc Endo Approach', 298853, 389);
insert into products (id, name, description, price, stock) values (197, 'Cabbage - Savoy', 'Supplement R Pulm Art with Nonaut Sub, Open Approach', 619122, 475);
insert into products (id, name, description, price, stock) values (198, 'Icecream - Dibs', 'Alteration of R Ankle with Synth Sub, Open Approach', 571262, 392);
insert into products (id, name, description, price, stock) values (199, 'Lemon Pepper', 'Bypass Thor Aorta Asc to L Pulm Art w Synth Sub, Perc Endo', 371538, 495);
insert into products (id, name, description, price, stock) values (200, 'Wine - White Cab Sauv.on', 'Revision of Radioact Elem in Resp Tract, Perc Endo Approach', 39226, 256);
