insert into products (id, name, description, price, stock, category_id) values (1, 'Wine - Riesling Alsace Ac 2001', 'Insertion of Pressure Sens into L Pulm Art, Perc Approach', 165950, 38, 67);
insert into products (id, name, description, price, stock, category_id) values (2, 'Beer - Paulaner Hefeweisse', 'Revision of Nonautologous Tissue Substitute in Urethra, Endo', 279781, 419, 66);
insert into products (id, name, description, price, stock, category_id) values (3, 'Muffins - Assorted', 'Removal of Int Fix from Lum Vertebra, Perc Approach', 779817, 213, 85);
insert into products (id, name, description, price, stock, category_id) values (4, 'Pastry - Apple Large', 'Fusion L Metacarpophal Jt w Autol Sub, Perc Endo', 469226, 486, 56);
insert into products (id, name, description, price, stock, category_id) values (5, 'Cranberries - Dry', 'Release Innominate Artery, Open Approach', 720200, 462, 63);
insert into products (id, name, description, price, stock, category_id) values (6, 'Pate - Liver', 'Destruction of Left Sacroiliac Joint, Percutaneous Approach', 800311, 180, 78);
insert into products (id, name, description, price, stock, category_id) values (7, 'Clam - Cherrystone', 'Supplement L Axilla Lymph w Nonaut Sub, Perc Endo', 454697, 401, 81);
insert into products (id, name, description, price, stock, category_id) values (8, 'Cornstarch', 'Replacement of Bi Ext Ear with Synth Sub, Open Approach', 273454, 173, 78);
insert into products (id, name, description, price, stock, category_id) values (9, 'Beef - Rib Roast, Capless', 'Drainage of Bi Fallopian Tube with Drain Dev, Via Opening', 247013, 407, 33);
insert into products (id, name, description, price, stock, category_id) values (10, 'Turkey - Breast, Double', 'Bypass Left Brachial Vein to Upper Vein, Open Approach', 556988, 403, 91);
insert into products (id, name, description, price, stock, category_id) values (11, 'Squash - Guords', 'Revision of Other Device in Abdominal Wall, Open Approach', 953358, 461, 83);
insert into products (id, name, description, price, stock, category_id) values (12, 'Corn - Mini', 'Removal of Synth Sub from L Pleural Cav, Perc Endo Approach', 72729, 485, 86);
insert into products (id, name, description, price, stock, category_id) values (13, 'Lady Fingers', 'Reattachment of Left Upper Leg Tendon, Perc Endo Approach', 412340, 353, 2);
insert into products (id, name, description, price, stock, category_id) values (14, 'Eel - Smoked', 'Transfer Facial Nerve to Trigeminal Nerve, Open Approach', 902424, 142, 11);
insert into products (id, name, description, price, stock, category_id) values (15, 'Corn - On The Cob', 'Destruction of Left Epididymis, Open Approach', 979631, 308, 20);
insert into products (id, name, description, price, stock, category_id) values (16, 'Pasta - Penne Primavera, Single', 'Restrict of R Inqnl Lymph with Intralum Dev, Perc Approach', 214022, 486, 54);
insert into products (id, name, description, price, stock, category_id) values (17, 'Napkin White - Starched', 'Repair Right Upper Leg, Percutaneous Approach', 728296, 149, 33);
insert into products (id, name, description, price, stock, category_id) values (18, 'Wanton Wrap', 'Occlusion of Right Hand Vein, Percutaneous Approach', 218757, 127, 57);
insert into products (id, name, description, price, stock, category_id) values (19, 'Soup - Campbells Pasta Fagioli', 'Bypass Pulm Trunk from Carotid with Autol Vn, Open Approach', 283555, 353, 11);
insert into products (id, name, description, price, stock, category_id) values (20, 'Salmon - Atlantic, Fresh, Whole', 'Repair Right Foot Tendon, Percutaneous Endoscopic Approach', 149932, 124, 71);
insert into products (id, name, description, price, stock, category_id) values (21, 'Vinegar - Cider', 'Excision of R Com Carotid, Open Approach, Diagn', 910505, 379, 21);
insert into products (id, name, description, price, stock, category_id) values (22, 'Milk Powder', 'Supplement Upper Vein with Nonaut Sub, Perc Approach', 64746, 424, 71);
insert into products (id, name, description, price, stock, category_id) values (23, 'Wine - Prosecco Valdobienne', 'Revision of Int Fix in R Glenoid Cav, Extern Approach', 200193, 458, 16);
insert into products (id, name, description, price, stock, category_id) values (24, 'Squash - Acorn', 'Removal of Extralum Dev from Vas Deferens, Via Opening', 934939, 257, 50);
insert into products (id, name, description, price, stock, category_id) values (25, 'Cheese Cheddar Processed', 'Repair Lumbar Nerve, Open Approach', 639060, 329, 44);
insert into products (id, name, description, price, stock, category_id) values (26, 'Milkettes - 2%', 'Introduction of Electrol/Water Bal into Up GI, Perc Approach', 434341, 12, 13);
insert into products (id, name, description, price, stock, category_id) values (27, 'Cheese - Grie Des Champ', 'Occlusion of R Main Bronc with Intralum Dev, Perc Approach', 36402, 58, 79);
insert into products (id, name, description, price, stock, category_id) values (28, 'Mustard - Individual Pkg', 'Revision of Ext Fix in R Radius, Perc Endo Approach', 769538, 425, 44);
insert into products (id, name, description, price, stock, category_id) values (29, 'Pasta - Rotini, Colour, Dry', 'Supplement Intracranial Vein with Autol Sub, Open Approach', 749309, 168, 98);
insert into products (id, name, description, price, stock, category_id) values (30, 'Juice - Ocean Spray Kiwi', 'Removal of Monitoring Device from Pleura, Perc Endo Approach', 879272, 460, 17);
insert into products (id, name, description, price, stock, category_id) values (31, 'Mix - Cocktail Strawberry Daiquiri', 'Drainage of Left Internal Mammary Lymphatic, Perc Approach', 940431, 380, 37);
insert into products (id, name, description, price, stock, category_id) values (32, 'Chocolate - Milk Coating', 'Destruction of Left Tympanic Membrane, Open Approach', 260501, 13, 12);
insert into products (id, name, description, price, stock, category_id) values (33, 'Aspic - Clear', 'Insert of Spacer into R Metacarpophal Jt, Perc Endo Approach', 548138, 128, 42);
insert into products (id, name, description, price, stock, category_id) values (34, 'Potatoes - Idaho 100 Count', 'Destruction of Right Humeral Head, Percutaneous Approach', 194530, 240, 68);
insert into products (id, name, description, price, stock, category_id) values (35, 'Beans - Black Bean, Dry', 'Destruction of Stomach, Pylorus, Via Opening', 843311, 139, 82);
insert into products (id, name, description, price, stock, category_id) values (36, 'Pear - Asian', 'Revision of Feeding Dev in Up Intest Tract, Extern Approach', 883133, 17, 28);
insert into products (id, name, description, price, stock, category_id) values (37, 'Steam Pan Full Lid', 'Introduce of Oth Therap Subst into Periph Art, Open Approach', 77564, 19, 92);
insert into products (id, name, description, price, stock, category_id) values (38, 'Beets - Golden', 'Revision of Drainage Device in Larynx, External Approach', 154488, 466, 47);
insert into products (id, name, description, price, stock, category_id) values (39, 'Nut - Pine Nuts, Whole', 'Reposition Sternum with Rigid Plate Fix, Perc Endo Approach', 828535, 203, 49);
insert into products (id, name, description, price, stock, category_id) values (40, 'Chocolate - Compound Coating', 'Stereotactic Gamma Beam Radiosurgery of Pelvis Lymphatics', 172367, 116, 99);
insert into products (id, name, description, price, stock, category_id) values (41, 'Chives - Fresh', 'Removal of Infusion Device from Pancreas, Perc Endo Approach', 619972, 237, 28);
insert into products (id, name, description, price, stock, category_id) values (42, 'Ecolab Digiclean Mild Fm', 'Removal of Bandage on Left Upper Arm', 50943, 216, 74);
insert into products (id, name, description, price, stock, category_id) values (43, 'Soup - Campbells, Butternut', 'Drainage of R Hip Jt with Drain Dev, Perc Endo Approach', 729527, 386, 43);
insert into products (id, name, description, price, stock, category_id) values (44, 'Juice - V8 Splash', 'Release Left Ankle Joint, Percutaneous Approach', 419118, 216, 46);
insert into products (id, name, description, price, stock, category_id) values (45, 'Sultanas', 'Monitoring of Cardiac Sound, External Approach', 941203, 336, 71);
insert into products (id, name, description, price, stock, category_id) values (46, 'Salmon - Atlantic, Fresh, Whole', 'Tomo Nucl Med Imag of Head & Neck using Gallium 67', 150116, 304, 25);
insert into products (id, name, description, price, stock, category_id) values (47, 'Garam Masala Powder', 'Cochlear Implant Assessment using Audiometer', 226197, 12, 29);
insert into products (id, name, description, price, stock, category_id) values (48, 'Wine - Montecillo Rioja Crianza', 'Ultrasonography of Right Pulmonary Artery', 350082, 490, 40);
insert into products (id, name, description, price, stock, category_id) values (49, 'Nut - Cashews, Whole, Raw', 'Sensorineural Acuity Level Assessment', 985506, 416, 70);
insert into products (id, name, description, price, stock, category_id) values (50, 'Wine - Red, Gamay Noir', 'Bypass R Renal Vein to Low Vein with Autol Vn, Open Approach', 407420, 196, 1);
insert into products (id, name, description, price, stock, category_id) values (51, 'Asparagus - White, Canned', 'Supplement Cecum with Synthetic Substitute, Open Approach', 690509, 414, 35);
insert into products (id, name, description, price, stock, category_id) values (52, 'Instant Coffee', 'Ultrasonography of Bilateral Fallopian Tubes', 114891, 339, 42);
insert into products (id, name, description, price, stock, category_id) values (53, 'Chick Peas - Dried', 'Occlusion of Transverse Colon with Intraluminal Device, Endo', 544078, 43, 64);
insert into products (id, name, description, price, stock, category_id) values (54, 'Carbonated Water - White Grape', 'Supplement Duodenum with Nonaut Sub, Endo', 474465, 50, 18);
insert into products (id, name, description, price, stock, category_id) values (55, 'Ice Cream Bar - Hageen Daz To', 'Restriction of Face Artery with Extralum Dev, Perc Approach', 328328, 102, 49);
insert into products (id, name, description, price, stock, category_id) values (56, 'Veal - Loin', 'Drainage of R Int Jugular Vein, Open Approach, Diagn', 642665, 104, 45);
insert into products (id, name, description, price, stock, category_id) values (57, 'Glaze - Apricot', 'Removal of Autol Sub from R Radius, Perc Approach', 367900, 340, 54);
insert into products (id, name, description, price, stock, category_id) values (58, 'Calvados - Boulard', 'Occlusion of Cecum, Percutaneous Endoscopic Approach', 68160, 298, 91);
insert into products (id, name, description, price, stock, category_id) values (59, 'Sugar - Brown', 'Removal of Radioact Elem from Resp Tract, Extern Approach', 300874, 104, 32);
insert into products (id, name, description, price, stock, category_id) values (60, 'Wine - Savigny - Les - Beaune', 'Dilation of Left Radial Artery, Bifurcation, Open Approach', 240586, 302, 56);
insert into products (id, name, description, price, stock, category_id) values (61, 'Bread - Hamburger Buns', 'Destruction of Right Colic Artery, Open Approach', 815030, 327, 78);
insert into products (id, name, description, price, stock, category_id) values (62, 'Bread Base - Gold Formel', 'Occlusion of Common Bile Duct, Endo', 18140, 274, 81);
insert into products (id, name, description, price, stock, category_id) values (63, 'Beets - Mini Golden', 'Resection of Sigmoid Colon, Open Approach', 491750, 142, 89);
insert into products (id, name, description, price, stock, category_id) values (64, 'Tofu - Soft', 'Repair Cardiovascular Sys in POC w Oth Dev, Perc Endo', 244399, 46, 28);
insert into products (id, name, description, price, stock, category_id) values (65, 'Soup - Campbells - Chicken Noodle', 'Reposition Right Fibula, External Approach', 383890, 426, 86);
insert into products (id, name, description, price, stock, category_id) values (66, 'Island Oasis - Lemonade', 'Repair Right Carpal Joint, External Approach', 353332, 239, 80);
insert into products (id, name, description, price, stock, category_id) values (67, 'Beans - Turtle, Black, Dry', 'Excision of Adenoids, Open Approach', 425561, 181, 99);
insert into products (id, name, description, price, stock, category_id) values (68, 'Oil - Coconut', 'Reposition Left Humeral Head, Percutaneous Approach', 703084, 365, 45);
insert into products (id, name, description, price, stock, category_id) values (69, 'Tuna - Yellowfin', 'Alteration of Face with Nonaut Sub, Perc Approach', 664348, 305, 6);
insert into products (id, name, description, price, stock, category_id) values (70, 'Wine - White, Chardonnay', 'Excision of Left Upper Lobe Bronchus, Perc Approach, Diagn', 567803, 160, 64);
insert into products (id, name, description, price, stock, category_id) values (71, 'Beer - Upper Canada Lager', 'Drainage of Left Hand Vein, Percutaneous Approach, Diagn', 111127, 233, 77);
insert into products (id, name, description, price, stock, category_id) values (72, 'Wine - Rosso Del Veronese Igt', 'Division of Right Shoulder Bursa and Ligament, Perc Approach', 929854, 192, 31);
insert into products (id, name, description, price, stock, category_id) values (73, 'Tomatoes - Grape', 'Control Bleeding in Gastrointestinal Tract, Endo', 657059, 309, 93);
insert into products (id, name, description, price, stock, category_id) values (74, 'Lobster - Canned Premium', 'Resection of Bilateral Vas Deferens, Open Approach', 891226, 370, 38);
insert into products (id, name, description, price, stock, category_id) values (75, 'Veal - Brisket, Provimi,bnls', 'Replacement of L Toe Phalanx with Nonaut Sub, Perc Approach', 512830, 63, 37);
insert into products (id, name, description, price, stock, category_id) values (76, 'Red Currants', 'Irrigate Epidural Space w Irrigat, Perc, Diagn', 557956, 407, 45);
insert into products (id, name, description, price, stock, category_id) values (77, 'Chambord Royal', 'Division of Right Lower Leg Muscle, Perc Endo Approach', 172948, 44, 6);
insert into products (id, name, description, price, stock, category_id) values (78, 'Beef - Tenderloin', 'Destruction of Left Tympanic Membrane, Endo', 455974, 169, 33);
insert into products (id, name, description, price, stock, category_id) values (79, 'Sugar - Palm', 'Fusion of 2-4 L Jt, Post Appr P Col, Open Approach', 372022, 316, 8);
insert into products (id, name, description, price, stock, category_id) values (80, 'Milk - Chocolate 500ml', 'Revision of Nonaut Sub in L Finger Phalanx, Open Approach', 10724, 373, 59);
insert into products (id, name, description, price, stock, category_id) values (81, 'Muffin Mix - Chocolate Chip', 'Repair Left Hand Bursa and Ligament, Open Approach', 879336, 443, 26);
insert into products (id, name, description, price, stock, category_id) values (82, 'Cocktail Napkin Blue', 'Reposition Left Renal Artery, Perc Endo Approach', 977952, 352, 37);
insert into products (id, name, description, price, stock, category_id) values (83, 'Wine - Cava Aria Estate Brut', 'Fluoroscopy of R Com Carotid using Oth Contrast', 273808, 88, 73);
insert into products (id, name, description, price, stock, category_id) values (84, 'Flax Seed', 'Ear, Nose, Sinus, Extraction', 125929, 361, 18);
insert into products (id, name, description, price, stock, category_id) values (85, 'Sauce - Ranch Dressing', 'Drainage of R Abd Bursa/Lig with Drain Dev, Perc Approach', 803111, 322, 30);
insert into products (id, name, description, price, stock, category_id) values (86, 'Peppercorns - Green', 'Bypass R Ventricle to Pulm Trunk w Nonaut Sub, Perc Endo', 683074, 396, 31);
insert into products (id, name, description, price, stock, category_id) values (87, 'Sandwich Wrap', 'Release Right Vas Deferens, Open Approach', 339762, 139, 100);
insert into products (id, name, description, price, stock, category_id) values (88, 'Pepper - Cubanelle', 'Male Reproductive System, Reattachment', 617583, 170, 47);
insert into products (id, name, description, price, stock, category_id) values (89, 'Napkin - Beverage 1 Ply', 'Revise Drain Dev in R Metacarpophal Jt, Perc Endo', 516094, 172, 34);
insert into products (id, name, description, price, stock, category_id) values (90, 'Wine - Touraine Azay - Le - Rideau', 'Drainage of Right Eye, External Approach, Diagnostic', 376740, 246, 17);
insert into products (id, name, description, price, stock, category_id) values (91, 'Wine - Barolo Fontanafredda', 'Revision of Nonaut Sub in R Femur Shaft, Perc Endo Approach', 33815, 85, 2);
insert into products (id, name, description, price, stock, category_id) values (92, 'Bandage - Finger Cots', 'Repair Left Tarsal Joint, Percutaneous Endoscopic Approach', 650629, 184, 80);
insert into products (id, name, description, price, stock, category_id) values (93, 'Spinach - Frozen', 'Fragmentation in Right Hepatic Duct, Via Opening', 533537, 412, 7);
insert into products (id, name, description, price, stock, category_id) values (94, 'Apricots Fresh', 'Extirpation of Matter from Penis, Percutaneous Approach', 592857, 149, 97);
insert into products (id, name, description, price, stock, category_id) values (95, 'Bread - Raisin Walnut Pull', 'Division of Right Upper Femur, Percutaneous Approach', 503326, 463, 43);
insert into products (id, name, description, price, stock, category_id) values (96, 'Bread - Pain Au Liat X12', 'Bypass Cecum to Sigmoid Colon with Autol Sub, Endo', 465017, 261, 23);
insert into products (id, name, description, price, stock, category_id) values (97, 'Gatorade - Cool Blue Raspberry', 'Fusion L Metacarpophal Jt w Int Fix, Perc Endo', 77669, 95, 90);
insert into products (id, name, description, price, stock, category_id) values (98, 'Towel Dispenser', 'Replacement of Occip Jt with Nonaut Sub, Open Approach', 168565, 369, 85);
insert into products (id, name, description, price, stock, category_id) values (99, 'Venison - Denver Leg Boneless', 'Inspection of Left Buttock, Open Approach', 328073, 499, 54);
insert into products (id, name, description, price, stock, category_id) values (100, 'Pork - Backfat', 'Dilate R Radial Art, Bifurc, w 3 Intralum Dev, Open', 446561, 406, 86);
insert into products (id, name, description, price, stock, category_id) values (101, 'Veal - Insides, Grains', 'Removal of Int Fix from R Tibia, Extern Approach', 839658, 151, 64);
insert into products (id, name, description, price, stock, category_id) values (102, 'Turkey - Whole, Fresh', 'CT Scan of L Ankle using Oth Contrast', 897927, 361, 3);
insert into products (id, name, description, price, stock, category_id) values (103, 'Table Cloth 62x114 Colour', 'Dilation of Left Hepatic Duct, Via Opening', 956219, 368, 64);
insert into products (id, name, description, price, stock, category_id) values (104, 'Juice - V8 Splash', 'Removal of Drainage Device from Thoracic Duct, Open Approach', 892199, 376, 61);
insert into products (id, name, description, price, stock, category_id) values (105, 'Sauce - Hollandaise', 'Insertion of Spacer into L Finger Phalanx Jt, Open Approach', 187906, 133, 95);
insert into products (id, name, description, price, stock, category_id) values (106, 'Chinese Foods - Thick Noodles', 'Division of Left Rib, Percutaneous Endoscopic Approach', 419038, 319, 3);
insert into products (id, name, description, price, stock, category_id) values (107, 'Muffin - Banana Nut Individual', 'Resection of Hard Palate, Open Approach', 326453, 278, 24);
insert into products (id, name, description, price, stock, category_id) values (108, 'Wine - Magnotta - Bel Paese White', 'Transfuse of Autol Globulin into Central Art, Perc Approach', 853472, 456, 72);
insert into products (id, name, description, price, stock, category_id) values (109, 'Boogies', 'Repair Left Shoulder Bursa and Ligament, Perc Approach', 598391, 292, 28);
insert into products (id, name, description, price, stock, category_id) values (110, 'Honey - Comb', 'Excision of Head and Neck Tendon, Open Approach, Diagnostic', 456546, 255, 10);
insert into products (id, name, description, price, stock, category_id) values (111, 'Salt - Celery', 'Restriction of Lower Artery, Percutaneous Approach', 83161, 29, 14);
insert into products (id, name, description, price, stock, category_id) values (112, 'Cake - Mini Cheesecake', 'Revise Nonaut Sub in Vagina & Cul-de-sac, Perc Endo', 571798, 140, 52);
insert into products (id, name, description, price, stock, category_id) values (113, 'Milk - Chocolate 500ml', 'Drainage of Left Temporal Bone, Percutaneous Approach, Diagn', 436132, 490, 33);
insert into products (id, name, description, price, stock, category_id) values (114, 'Cheese - Ermite Bleu', 'Drainage of R Mid Lobe Bronc with Drain Dev, Perc Approach', 997375, 332, 9);
insert into products (id, name, description, price, stock, category_id) values (115, 'Celery Root', 'Repair Right Brachial Vein, Percutaneous Endoscopic Approach', 782697, 382, 48);
insert into products (id, name, description, price, stock, category_id) values (116, 'Aspic - Amber', 'Bypass L Int Iliac Art to B Femor A w Autol Vn, Perc Endo', 519969, 381, 47);
insert into products (id, name, description, price, stock, category_id) values (117, 'Flour Dark Rye', 'Supplement Left Foot Artery with Autol Sub, Perc Approach', 812642, 222, 93);
insert into products (id, name, description, price, stock, category_id) values (118, 'Compound - Pear', 'Excision of Left External Carotid Artery, Open Approach', 974554, 45, 66);
insert into products (id, name, description, price, stock, category_id) values (119, 'Rye Special Old', 'Repair Left Choroid, Open Approach', 64270, 112, 50);
insert into products (id, name, description, price, stock, category_id) values (120, 'Orange - Blood', 'Drainage of Oculomotor Nerve, Perc Endo Approach', 477280, 151, 49);
insert into products (id, name, description, price, stock, category_id) values (121, 'Worcestershire Sauce', 'Bypass Thor Aorta Desc to L Pulm Art w Zooplastic, Perc Endo', 697201, 431, 28);
insert into products (id, name, description, price, stock, category_id) values (122, 'Towel Dispenser', 'Release Peroneal Nerve, Percutaneous Approach', 847502, 228, 36);
insert into products (id, name, description, price, stock, category_id) values (123, 'Chambord Royal', 'Ultrasonography of Right Pulmonary Artery', 724563, 400, 90);
insert into products (id, name, description, price, stock, category_id) values (124, 'Danishes - Mini Cheese', 'LDR Brachytherapy of Thymus using Palladium 103', 77916, 105, 51);
insert into products (id, name, description, price, stock, category_id) values (125, 'Chocolate - Dark', 'Reposition Left Fibula, External Approach', 316745, 12, 81);
insert into products (id, name, description, price, stock, category_id) values (126, 'Bread Ww Cluster', 'Removal of Autol Sub from L Finger Phalanx Jt, Open Approach', 819163, 259, 92);
insert into products (id, name, description, price, stock, category_id) values (127, 'Beef - Rouladin, Sliced', 'Revision of Nonaut Sub in L Metatarsophal Jt, Perc Approach', 776941, 140, 9);
insert into products (id, name, description, price, stock, category_id) values (128, 'Cherries - Fresh', 'Revision of Autol Sub in R Radius, Perc Approach', 374084, 81, 11);
insert into products (id, name, description, price, stock, category_id) values (129, 'Pasta - Elbows, Macaroni, Dry', 'Occlusion of Right Ureter with Extralum Dev, Open Approach', 986172, 39, 11);
insert into products (id, name, description, price, stock, category_id) values (130, 'Pepper - Scotch Bonnet', 'Excision of Left Femoral Vein, Percutaneous Approach, Diagn', 177155, 145, 71);
insert into products (id, name, description, price, stock, category_id) values (131, 'Bar - Sweet And Salty Chocolate', 'Reposition Cerv Jt with Int Fix, Extern Approach', 907230, 260, 64);
insert into products (id, name, description, price, stock, category_id) values (132, 'Soup - Base Broth Beef', 'Replacement of Lesser Omentum with Autol Sub, Open Approach', 563863, 500, 1);
insert into products (id, name, description, price, stock, category_id) values (133, 'Venison - Ground', 'Replace of L Pulm Vein with Autol Sub, Perc Endo Approach', 292554, 21, 77);
insert into products (id, name, description, price, stock, category_id) values (134, 'Chocolate - Dark Callets', 'Drainage of Occipital-cervical Joint, Percutaneous Approach', 854371, 396, 17);
insert into products (id, name, description, price, stock, category_id) values (135, 'Sauce - Apple, Unsweetened', 'Nonspoken Language Treatment using Other Equipment', 924676, 445, 64);
insert into products (id, name, description, price, stock, category_id) values (136, 'Basil - Fresh', 'Replace of L Knee Jt, Tibial with Synth Sub, Open Approach', 318635, 253, 73);
insert into products (id, name, description, price, stock, category_id) values (137, 'Grapes - Black', 'Extirpation of Matter from Median Nerve, Perc Endo Approach', 70784, 213, 48);
insert into products (id, name, description, price, stock, category_id) values (138, 'Appetizer - Veg Assortment', 'Drainage of Right Ankle Joint, Percutaneous Approach, Diagn', 972163, 215, 7);
insert into products (id, name, description, price, stock, category_id) values (139, 'Roe - White Fish', 'Revision of Spacer in Occip Jt, Perc Approach', 649654, 334, 71);
insert into products (id, name, description, price, stock, category_id) values (140, 'Bread - Raisin', 'Dilate Intracran Art, Bifurc, w 2 Intralum Dev, Open', 475528, 325, 56);
insert into products (id, name, description, price, stock, category_id) values (141, 'Soup - Canadian Pea, Dry Mix', 'Revision of Int Fix in L Low Femur, Extern Approach', 369162, 379, 56);
insert into products (id, name, description, price, stock, category_id) values (142, 'Mix - Cocktail Strawberry Daiquiri', 'Release Right Neck Lymphatic, Percutaneous Approach', 933182, 378, 38);
insert into products (id, name, description, price, stock, category_id) values (143, 'Sauce - Mint', 'Resection of Right Neck Lymphatic, Open Approach', 97921, 370, 38);
insert into products (id, name, description, price, stock, category_id) values (144, 'Cup - 8oz Coffee Perforated', 'Drainage of Right Hand Muscle, Perc Endo Approach', 776820, 457, 29);
insert into products (id, name, description, price, stock, category_id) values (145, 'Energy Drink Red Bull', 'Restriction of L Ext Jugular Vein, Perc Endo Approach', 515496, 123, 43);
insert into products (id, name, description, price, stock, category_id) values (146, 'Pasta - Elbows, Macaroni, Dry', 'Insertion of Monitor Dev into Bladder, Perc Endo Approach', 770560, 286, 35);
insert into products (id, name, description, price, stock, category_id) values (147, 'Veal - Inside, Choice', 'Bypass Bilateral Vas Deferens to R Vas Def, Open Approach', 720622, 440, 100);
insert into products (id, name, description, price, stock, category_id) values (148, 'Crush - Orange, 355ml', 'Dilate L Peroneal Art, Bifurc, w 4+ Intralum Dev, Open', 972647, 484, 19);
insert into products (id, name, description, price, stock, category_id) values (149, 'Bread - Sour Batard', 'Dilation of Mitral Valve, Percutaneous Endoscopic Approach', 590255, 37, 2);
insert into products (id, name, description, price, stock, category_id) values (150, 'Wooden Mop Handle', 'Repair Face Subcutaneous Tissue and Fascia, Open Approach', 858012, 18, 96);
insert into products (id, name, description, price, stock, category_id) values (151, 'Nantucket - 518ml', 'Revise of Synth Sub in L Hip Jt, Femoral, Perc Endo Approach', 857800, 393, 69);
insert into products (id, name, description, price, stock, category_id) values (152, 'Cheese - Perron Cheddar', 'Replace of L Face Vein with Autol Sub, Perc Endo Approach', 889503, 64, 12);
insert into products (id, name, description, price, stock, category_id) values (153, 'Pastry - Choclate Baked', 'Supplement L Abd Bursa/Lig with Nonaut Sub, Open Approach', 486092, 202, 12);
insert into products (id, name, description, price, stock, category_id) values (154, 'Pastry - Lemon Danish - Mini', 'Repair Left Lung, Endo', 429462, 201, 78);
insert into products (id, name, description, price, stock, category_id) values (155, 'Octopus - Baby, Cleaned', 'Replacement of L Patella with Nonaut Sub, Perc Endo Approach', 541105, 193, 38);
insert into products (id, name, description, price, stock, category_id) values (156, 'Bok Choy - Baby', 'Drain of L Palatine Bone with Drain Dev, Perc Endo Approach', 563392, 267, 87);
insert into products (id, name, description, price, stock, category_id) values (157, 'Nut - Almond, Blanched, Whole', 'Transfuse Nonaut Red Blood Cells in Periph Vein, Perc', 511581, 476, 17);
insert into products (id, name, description, price, stock, category_id) values (158, 'Soy Protein', 'Measure of Cardiac Sampl & Pressure, R Heart, Perc Approach', 377227, 310, 58);
insert into products (id, name, description, price, stock, category_id) values (159, 'Anchovy In Oil', 'Excision of Left Common Iliac Vein, Open Approach', 183403, 392, 52);
insert into products (id, name, description, price, stock, category_id) values (160, 'Pork - Loin, Center Cut', 'Bypass Left Hepatic Duct to R Hep Duc, Perc Endo Approach', 388287, 111, 88);
insert into products (id, name, description, price, stock, category_id) values (161, 'V8 - Vegetable Cocktail', 'Transfuse of Autol Factor IX into Periph Vein, Open Approach', 337754, 262, 16);
insert into products (id, name, description, price, stock, category_id) values (162, 'Island Oasis - Ice Cream Mix', 'Bypass Bi Ureter to Ileocutan w Synth Sub, Perc Endo', 652393, 435, 22);
insert into products (id, name, description, price, stock, category_id) values (163, 'Wine - Red, Marechal Foch', 'Bypass L Ureter to R Ureter w Autol Sub, Perc Endo', 80647, 81, 68);
insert into products (id, name, description, price, stock, category_id) values (164, 'Petite Baguette', 'Revision of Synth Sub in Vas Deferens, Extern Approach', 796156, 427, 96);
insert into products (id, name, description, price, stock, category_id) values (165, 'Wine - White, French Cross', 'Drainage of Pons with Drainage Device, Percutaneous Approach', 263350, 107, 73);
insert into products (id, name, description, price, stock, category_id) values (166, 'Shiratamako - Rice Flour', 'Restrict of Duodenum with Extralum Dev, Perc Endo Approach', 501802, 332, 1);
insert into products (id, name, description, price, stock, category_id) values (167, 'Chocolate Bar - Oh Henry', 'Excision of Left Temporal Artery, Perc Approach, Diagn', 93913, 150, 77);
insert into products (id, name, description, price, stock, category_id) values (168, 'Potatoes - Instant, Mashed', 'Restriction of L Innom Vein with Intralum Dev, Open Approach', 358009, 465, 5);
insert into products (id, name, description, price, stock, category_id) values (169, 'Muffin Hinge - 211n', 'Supplement Left Tarsal with Nonaut Sub, Open Approach', 392485, 59, 25);
insert into products (id, name, description, price, stock, category_id) values (170, 'Tart Shells - Savory, 3', 'Drainage of Bilateral Breast with Drain Dev, Extern Approach', 774417, 228, 70);
insert into products (id, name, description, price, stock, category_id) values (171, 'Monkfish - Fresh', 'Repair Left Foot Artery, Open Approach', 294047, 393, 42);
insert into products (id, name, description, price, stock, category_id) values (172, 'Lambcasing', 'Reposition Transverse Colon, Perc Endo Approach', 870611, 46, 63);
insert into products (id, name, description, price, stock, category_id) values (173, 'Pear - Packum', 'Revision of Autol Sub in Low Back, Perc Endo Approach', 411960, 417, 26);
insert into products (id, name, description, price, stock, category_id) values (174, 'Nantucket - Kiwi Berry Cktl.', 'Fusion of Right Ankle Joint with Ext Fix, Perc Approach', 221792, 426, 52);
insert into products (id, name, description, price, stock, category_id) values (175, 'Wine - Kwv Chenin Blanc South', 'Destruction of Tonsils, Open Approach', 27911, 346, 21);
insert into products (id, name, description, price, stock, category_id) values (176, 'Soup V8 Roasted Red Pepper', 'Extirpation of Matter from Left Hepatic Duct, Endo', 185394, 157, 80);
insert into products (id, name, description, price, stock, category_id) values (177, 'Beef - Rib Eye Aaa', 'Reposition Superior Mesenteric Artery, Perc Endo Approach', 64648, 421, 66);
insert into products (id, name, description, price, stock, category_id) values (178, 'Mushroom - Chanterelle Frozen', 'Release Thoracic Sympathetic Nerve, Percutaneous Approach', 948211, 360, 50);
insert into products (id, name, description, price, stock, category_id) values (179, 'Leeks - Baby, White', 'Occlusion Mesenteric Lymph w Intralum Dev, Perc', 30609, 497, 14);
insert into products (id, name, description, price, stock, category_id) values (180, 'Wine - Beaujolais Villages', 'Supplement Left Middle Finger with Synth Sub, Open Approach', 309123, 285, 61);
insert into products (id, name, description, price, stock, category_id) values (181, 'Energy Drink - Redbull 355ml', 'Bypass 3 Cor Art from R Int Mammary w Nonaut Sub, Perc Endo', 750099, 281, 4);
insert into products (id, name, description, price, stock, category_id) values (182, 'Snapple Raspberry Tea', 'Bypass Azygos Vein to Up Vein w Autol Sub, Perc Endo', 893073, 481, 75);
insert into products (id, name, description, price, stock, category_id) values (183, 'Potatoes - Peeled', 'Release Right Patella, Percutaneous Approach', 752724, 445, 43);
insert into products (id, name, description, price, stock, category_id) values (184, 'Hersey Shakes', 'Insert Limb Length Dev in R Low Femur, Perc Endo', 945862, 337, 37);
insert into products (id, name, description, price, stock, category_id) values (185, 'Parsley - Dried', 'Division of R Up Leg Subcu/Fascia, Perc Approach', 528135, 19, 33);
insert into products (id, name, description, price, stock, category_id) values (186, 'Persimmons', 'Extirpation of Matter from Left Hand Artery, Open Approach', 404243, 363, 1);
insert into products (id, name, description, price, stock, category_id) values (187, 'Water - Spring Water 500ml', 'Restriction of L Great Saphenous, Perc Endo Approach', 250319, 262, 6);
insert into products (id, name, description, price, stock, category_id) values (188, 'Nacho Chips', 'Drainage of Left Thyroid Gland Lobe, Open Approach, Diagn', 931472, 66, 77);
insert into products (id, name, description, price, stock, category_id) values (189, 'Glass Clear 8 Oz', 'Dilation of Small Intestine, Perc Endo Approach', 476157, 348, 65);
insert into products (id, name, description, price, stock, category_id) values (190, 'Pork - Belly Fresh', 'Dilation of L Fem Art with 2 Drug-elut, Perc Approach', 47445, 138, 49);
insert into products (id, name, description, price, stock, category_id) values (191, 'Rabbit - Saddles', 'Excision of Uterus, Endo', 667242, 277, 85);
insert into products (id, name, description, price, stock, category_id) values (192, 'Oil - Safflower', 'Revision of Autol Sub in R Extraoc Muscle, Open Approach', 749688, 223, 87);
insert into products (id, name, description, price, stock, category_id) values (193, 'Longos - Grilled Veg Sandwiches', 'Destruction of Left Vocal Cord, Via Opening', 677823, 69, 93);
insert into products (id, name, description, price, stock, category_id) values (194, 'Cornstarch', 'Replacement of Ampulla Vater with Nonaut Sub, Open Approach', 582115, 270, 6);
insert into products (id, name, description, price, stock, category_id) values (195, 'Bread - Wheat Baguette', 'Division of Uterine Supporting Structure, Open Approach', 575154, 47, 2);
insert into products (id, name, description, price, stock, category_id) values (196, 'Stock - Chicken, White', 'Removal of Nonaut Sub from Up Jaw, Perc Endo Approach', 149861, 305, 63);
insert into products (id, name, description, price, stock, category_id) values (197, 'Whmis Spray Bottle Graduated', 'Reposition Left Parietal Bone with Int Fix, Open Approach', 465282, 91, 3);
insert into products (id, name, description, price, stock, category_id) values (198, 'Wine - Bourgogne 2002, La', 'Removal of Intralum Dev from Gallbladder, Open Approach', 786200, 83, 68);
insert into products (id, name, description, price, stock, category_id) values (199, 'Yams', 'Supplement Lumbosacral Disc with Synth Sub, Perc Approach', 268568, 287, 69);
insert into products (id, name, description, price, stock, category_id) values (200, 'Carrots - Jumbo', 'Destruction of Hepatic Vein, Percutaneous Approach', 744337, 117, 12);
