insert into products (id, name, description, price, stock, store_id) values (1, 'Island Oasis - Banana Daiquiri', 'HDR Brachytherapy of Rectum using Oth Isotope', 449338, 282, 2);
insert into products (id, name, description, price, stock, store_id) values (2, 'Bread - Roll, Italian', 'Insertion of Spacer into Coccygeal Joint, Perc Endo Approach', 820081, 245, 61);
insert into products (id, name, description, price, stock, store_id) values (3, 'Beer - Sleemans Cream Ale', 'Alteration of Neck with Synthetic Substitute, Perc Approach', 123587, 153, 22);
insert into products (id, name, description, price, stock, store_id) values (4, 'Mushroom - Trumpet, Dry', 'Insertion of Infusion Device into R Axilla, Perc Approach', 979349, 13, 34);
insert into products (id, name, description, price, stock, store_id) values (5, 'Wine - Jaboulet Cotes Du Rhone', 'Dilate L Com Iliac Art, Bifurc, w 3 Drug-elut, Perc Endo', 883519, 408, 87);
insert into products (id, name, description, price, stock, store_id) values (6, 'Grapes - Black', 'Reposition Right Abdomen Tendon, Open Approach', 202938, 464, 91);
insert into products (id, name, description, price, stock, store_id) values (7, 'Muffin Mix - Blueberry', 'Removal of Autol Sub from Prostate/Seminal Ves, Endo', 637041, 86, 14);
insert into products (id, name, description, price, stock, store_id) values (8, 'Bread Sour Rolls', 'Excision of Abdominal Wall, External Approach', 431933, 12, 94);
insert into products (id, name, description, price, stock, store_id) values (9, 'Squid - Breaded', 'Bypass Abdominal Aorta to Lower Artery, Open Approach', 640375, 373, 60);
insert into products (id, name, description, price, stock, store_id) values (10, 'Assorted Desserts', 'Drainage of Right Rib, Percutaneous Endoscopic Approach', 698688, 7, 66);
insert into products (id, name, description, price, stock, store_id) values (11, 'Juice - Lime', 'Insertion of Infusion Device into Ovary, Perc Endo Approach', 992815, 12, 4);
insert into products (id, name, description, price, stock, store_id) values (12, 'Cut Wakame - Hanawakaba', 'Dilation of Duodenum with Intraluminal Device, Open Approach', 860436, 481, 87);
insert into products (id, name, description, price, stock, store_id) values (13, 'Shrimp - Baby, Cold Water', 'Bypass L Com Iliac Art to R Com Ilia w Nonaut Sub, Open', 738819, 373, 65);
insert into products (id, name, description, price, stock, store_id) values (14, 'Coffee Beans - Chocolate', 'Repair Left Temporomandibular Joint, External Approach', 304320, 65, 45);
insert into products (id, name, description, price, stock, store_id) values (15, 'Juice - Tomato, 10 Oz', 'Extirpation of Matter from Lingula Bronchus, Open Approach', 264271, 486, 30);
insert into products (id, name, description, price, stock, store_id) values (16, 'Bay Leaf Fresh', 'Revision of Autol Sub in R Elbow Jt, Perc Endo Approach', 903703, 307, 100);
insert into products (id, name, description, price, stock, store_id) values (17, 'Wakami Seaweed', 'Extirpation of Matter from R Axilla Lymph, Open Approach', 332725, 396, 15);
insert into products (id, name, description, price, stock, store_id) values (18, 'Steamers White', 'Revision of Nonaut Sub in Trachea, Perc Endo Approach', 652615, 423, 37);
insert into products (id, name, description, price, stock, store_id) values (19, 'Glucose', 'Drainage of Lumbar Vertebral Disc, Perc Approach, Diagn', 402496, 149, 87);
insert into products (id, name, description, price, stock, store_id) values (20, 'Crab - Dungeness, Whole', 'Plain Radiography of Bilateral Zygomatic Arches', 650362, 183, 46);
insert into products (id, name, description, price, stock, store_id) values (21, 'Pork - Ham, Virginia', 'Extirpation of Matter from R Retinal Vessel, Perc Approach', 266892, 267, 50);
insert into products (id, name, description, price, stock, store_id) values (22, 'Beef Ground Medium', 'Muscle Performance Assessment of Genitourinary System', 971109, 173, 92);
insert into products (id, name, description, price, stock, store_id) values (23, 'Muffin Mix - Blueberry', 'Removal of Drain Dev from R Sternoclav Jt, Perc Approach', 936940, 122, 12);
insert into products (id, name, description, price, stock, store_id) values (24, 'Alize Sunset', 'Map Thalamus, Percutaneous Endoscopic Approach', 616926, 308, 46);
insert into products (id, name, description, price, stock, store_id) values (25, 'Chocolate - Milk Coating', 'Plain Radiography of Spinal Arteries using Other Contrast', 968432, 402, 44);
insert into products (id, name, description, price, stock, store_id) values (26, 'Skewers - Bamboo', 'Bypass R Pulm Art from Innom Art w Zooplastic, Perc Endo', 260188, 61, 13);
insert into products (id, name, description, price, stock, store_id) values (27, 'Appetizer - Assorted Box', 'Drainage of L Inf Parathyroid, Perc Endo Approach, Diagn', 755087, 217, 96);
insert into products (id, name, description, price, stock, store_id) values (28, 'Bread Base - Italian', 'CT Scan of R Tracheobronc Tree using Oth Contrast', 918067, 479, 9);
insert into products (id, name, description, price, stock, store_id) values (29, 'Tomatoes - Cherry', 'Excision of Anus, Open Approach, Diagnostic', 620697, 385, 61);
insert into products (id, name, description, price, stock, store_id) values (30, 'Wine - Cava Aria Estate Brut', 'LDR Brachytherapy of Nasopharynx using Cesium 137', 727657, 268, 23);
insert into products (id, name, description, price, stock, store_id) values (31, 'Muffin - Banana Nut Individual', 'Remove Infusion Pump from Up Extrem Subcu/Fascia, Perc', 137080, 137, 15);
insert into products (id, name, description, price, stock, store_id) values (32, 'Squash - Pattypan, Yellow', 'Repair Acoustic Nerve, Open Approach', 430843, 182, 74);
insert into products (id, name, description, price, stock, store_id) values (33, 'Icecream - Dstk Strw Chseck', 'Occlusion of L Int Carotid, Perc Endo Approach', 370621, 20, 53);
insert into products (id, name, description, price, stock, store_id) values (34, 'Turkey - Whole, Fresh', 'Bypass R Int Iliac Art to B Ext Ilia w Nonaut Sub, Perc Endo', 708158, 341, 9);
insert into products (id, name, description, price, stock, store_id) values (35, 'Jolt Cola - Electric Blue', 'Control Bleeding in Right Foot, Percutaneous Approach', 849977, 340, 3);
insert into products (id, name, description, price, stock, store_id) values (36, 'Beans - Fava, Canned', 'Bypass L Subclav Art to L Low Leg Art w Synth Sub, Open', 66832, 481, 52);
insert into products (id, name, description, price, stock, store_id) values (37, 'Crush - Orange, 355ml', 'Introduce of High dose IL-2 into Central Vein, Perc Approach', 247721, 178, 23);
insert into products (id, name, description, price, stock, store_id) values (38, 'Pastry - Raisin Muffin - Mini', 'Alteration of Right Shoulder Region, Percutaneous Approach', 359961, 102, 97);
insert into products (id, name, description, price, stock, store_id) values (39, 'Steampan - Foil', 'Drainage of Right External Auditory Canal, Perc Approach', 618775, 335, 20);
insert into products (id, name, description, price, stock, store_id) values (40, 'Lettuce - Arugula', 'Drainage of Ileocecal Valve, Endo', 34994, 461, 61);
insert into products (id, name, description, price, stock, store_id) values (41, 'Wine - Zinfandel California 2002', 'Cranial Nerve Integrity Assessment of Neuro Head, Neck', 373596, 416, 45);
insert into products (id, name, description, price, stock, store_id) values (42, 'Melon - Honey Dew', 'Drainage of Peritoneum with Drainage Device, Open Approach', 97628, 420, 45);
insert into products (id, name, description, price, stock, store_id) values (43, 'Tomatoes - Roma', 'Beam Radiation of Chest Skin using Photons <1 MeV', 298316, 40, 70);
insert into products (id, name, description, price, stock, store_id) values (44, 'Wine - Zonnebloem Pinotage', 'Removal of Other Device from GU Tract, Via Opening', 163243, 259, 76);
insert into products (id, name, description, price, stock, store_id) values (45, 'Beef - Cooked, Corned', 'Fusion of Right Tarsal Joint with Nonaut Sub, Perc Approach', 996838, 58, 78);
insert into products (id, name, description, price, stock, store_id) values (46, 'Longos - Chicken Cordon Bleu', 'Excision of L Knee Bursa/Lig, Perc Approach, Diagn', 353312, 184, 88);
insert into products (id, name, description, price, stock, store_id) values (47, 'Fish - Halibut, Cold Smoked', 'Fusion Cerv Jt w Intbd Fus Dev, Post Appr P Col, Perc Endo', 681941, 500, 95);
insert into products (id, name, description, price, stock, store_id) values (48, 'Corn Kernels - Frozen', 'Bypass Com Bile Duct to Sm Int w Intralum Dev, Open', 251242, 350, 21);
insert into products (id, name, description, price, stock, store_id) values (49, 'Bread - Roll, Italian', 'Excision of Left Renal Artery, Open Approach, Diagnostic', 534928, 250, 77);
insert into products (id, name, description, price, stock, store_id) values (50, 'Pasta - Detalini, White, Fresh', 'Removal of Synth Sub from R Toe Phalanx Jt, Perc Approach', 74860, 123, 18);
insert into products (id, name, description, price, stock, store_id) values (51, 'Bread - Roll, Soft White Round', 'Removal of Infusion Device from Low Vein, Perc Endo Approach', 106478, 390, 95);
insert into products (id, name, description, price, stock, store_id) values (52, 'Wine - Red, Pinot Noir, Chateau', 'Dilation of Left Ureter, Via Natural or Artificial Opening', 291164, 477, 15);
insert into products (id, name, description, price, stock, store_id) values (53, 'Butter Sweet', 'Supplement Intracran Art with Nonaut Sub, Open Approach', 614387, 409, 97);
insert into products (id, name, description, price, stock, store_id) values (54, 'Shrimp - Black Tiger 8 - 12', 'Extraction of Left Frontal Sinus, Perc Endo Approach', 648634, 399, 6);
insert into products (id, name, description, price, stock, store_id) values (55, 'Island Oasis - Banana Daiquiri', 'Insertion of Infusion Dev into R Knee Jt, Perc Endo Approach', 502166, 66, 16);
insert into products (id, name, description, price, stock, store_id) values (56, 'Beer - Sleeman Fine Porter', 'Alteration of Right Lower Leg with Synth Sub, Perc Approach', 66996, 480, 80);
insert into products (id, name, description, price, stock, store_id) values (57, 'Butter - Pod', 'Revision of Spacer in Left Carpal Joint, Perc Endo Approach', 819597, 161, 92);
insert into products (id, name, description, price, stock, store_id) values (58, 'Sauce - Fish 25 Ozf Bottle', 'Drain Head & Neck Bursa/Lig w Drain Dev, Perc Endo', 635824, 237, 39);
insert into products (id, name, description, price, stock, store_id) values (59, 'Plums - Red', 'Computerized Tomography (CT Scan) of Thoracic Aorta', 45629, 318, 92);
insert into products (id, name, description, price, stock, store_id) values (60, 'Vinegar - Rice', 'Introduce of High dose IL-2 into Central Vein, Open Approach', 288213, 156, 13);
insert into products (id, name, description, price, stock, store_id) values (61, 'Fennel - Seeds', 'Repair Portal Vein, Open Approach', 908591, 255, 95);
insert into products (id, name, description, price, stock, store_id) values (62, 'Bread - Wheat Baguette', 'Excision of R Metacarpocarp Jt, Open Approach, Diagn', 51289, 57, 53);
insert into products (id, name, description, price, stock, store_id) values (63, 'Bagelers - Cinn / Brown', 'Excision of Right Face Vein, Percutaneous Approach', 349795, 219, 29);
insert into products (id, name, description, price, stock, store_id) values (64, 'Wine - Sogrape Mateus Rose', 'Destruction of Left Hip Bursa and Ligament, Perc Approach', 768173, 222, 49);
insert into products (id, name, description, price, stock, store_id) values (65, 'Lid - Translucent, 3.5 And 6 Oz', 'Removal of Nonaut Sub from L Glenoid Cav, Perc Approach', 518834, 408, 99);
insert into products (id, name, description, price, stock, store_id) values (66, 'Ecolab - Balanced Fusion', 'Dilate Low Art, Bifurc, w Drug-elut Intra, Perc Endo', 943961, 45, 100);
insert into products (id, name, description, price, stock, store_id) values (67, 'Foam Espresso Cup Plain White', 'Central Nervous System, Reposition', 431972, 416, 24);
insert into products (id, name, description, price, stock, store_id) values (68, 'Hickory Smoke, Liquid', 'Bypass L Atrium to L Pulm Art w Autol Art, Perc Endo', 466291, 332, 30);
insert into products (id, name, description, price, stock, store_id) values (69, 'Wine - Delicato Merlot', 'Drainage of Left Wrist Region, Perc Endo Approach', 902243, 20, 48);
insert into products (id, name, description, price, stock, store_id) values (70, 'Wine - Red, Lurton Merlot De', 'Supplement R Elbow with Autol Sub, Perc Endo Approach', 187327, 455, 3);
insert into products (id, name, description, price, stock, store_id) values (71, 'Cabbage Roll', 'Excision of Left Vertebral Vein, Open Approach, Diagnostic', 655970, 306, 11);
insert into products (id, name, description, price, stock, store_id) values (72, 'Bouq All Italian - Primerba', 'Drainage of Right Metacarpocarpal Joint, Open Approach', 864483, 314, 93);
insert into products (id, name, description, price, stock, store_id) values (73, 'Okra', 'Revision of Autol Sub in Hepatobil Duct, Perc Endo Approach', 251337, 165, 91);
insert into products (id, name, description, price, stock, store_id) values (74, 'Sage Derby', 'Dilation of Right Upper Lobe Bronchus, Open Approach', 829809, 393, 92);
insert into products (id, name, description, price, stock, store_id) values (75, 'Chocolate Bar - Oh Henry', 'Dilation of Abdominal Aorta with Intralum Dev, Perc Approach', 830948, 252, 19);
insert into products (id, name, description, price, stock, store_id) values (76, 'Nut - Hazelnut, Ground, Natural', 'Supplement R Up Arm Subcu/Fascia w Synth Sub, Open', 877274, 386, 87);
insert into products (id, name, description, price, stock, store_id) values (77, 'Soup - Campbells Tomato Ravioli', 'Removal of Drainage Device from Thymus, Open Approach', 630461, 175, 86);
insert into products (id, name, description, price, stock, store_id) values (78, 'Wine - White, Schroder And Schyl', 'Replace of R Metatarsotars Jt with Synth Sub, Open Approach', 580845, 338, 67);
insert into products (id, name, description, price, stock, store_id) values (79, 'Chinese Foods - Thick Noodles', 'Bypass L Com Iliac Art to R Ext Ilia w Autol Vn, Perc Endo', 99693, 312, 9);
insert into products (id, name, description, price, stock, store_id) values (80, 'Sugar - Brown', 'Insert of Infusion Dev into Pelvic Cav, Perc Endo Approach', 348776, 449, 48);
insert into products (id, name, description, price, stock, store_id) values (81, 'Bread - Multigrain, Loaf', 'Removal of Autol Sub from Periph Nrv, Open Approach', 487083, 455, 69);
insert into products (id, name, description, price, stock, store_id) values (82, 'Sobe - Berry Energy', 'Supplement Small Intestine with Autol Sub, Via Opening', 942870, 274, 95);
insert into products (id, name, description, price, stock, store_id) values (83, 'Olives - Green, Pitted', 'LDR Brachytherapy of R Breast using Iridium 192', 778587, 18, 51);
insert into products (id, name, description, price, stock, store_id) values (84, 'Shiratamako - Rice Flour', 'Supplement Left Iris with Autol Sub, Perc Approach', 130301, 65, 48);
insert into products (id, name, description, price, stock, store_id) values (85, 'Isomalt', 'Alteration of Left Axilla with Synth Sub, Open Approach', 305017, 470, 4);
insert into products (id, name, description, price, stock, store_id) values (86, 'Cookie Trail Mix', 'Dilation of L Subclav Art with 3 Drug-elut, Perc Approach', 77646, 60, 46);
insert into products (id, name, description, price, stock, store_id) values (87, 'Flour - Masa De Harina Mexican', 'Dilate L Com Iliac Art, Bifurc, w 2 Drug-elut, Open', 977108, 31, 51);
insert into products (id, name, description, price, stock, store_id) values (88, 'Coke - Classic, 355 Ml', 'Insertion of Neuro Lead into Cereb Vent, Perc Endo Approach', 488882, 64, 4);
insert into products (id, name, description, price, stock, store_id) values (89, 'Wine - Niagara Peninsula Vqa', 'Revision of Infusion Device in L Pleural Cav, Open Approach', 639515, 90, 24);
insert into products (id, name, description, price, stock, store_id) values (90, 'Island Oasis - Cappucino Mix', 'Resection of Left Orbit, Open Approach', 676320, 16, 34);
insert into products (id, name, description, price, stock, store_id) values (91, 'Carbonated Water - Blackberry', 'Removal of Splint on Right Upper Extremity', 994133, 247, 26);
insert into products (id, name, description, price, stock, store_id) values (92, 'Bread Base - Gold Formel', 'Dilate L Ext Iliac Art, Bifurc, w 3 Drug-elut, Perc', 987920, 419, 7);
insert into products (id, name, description, price, stock, store_id) values (93, 'Lemonade - Natural, 591 Ml', 'Occlusion L Int Jugular Vein w Extralum Dev, Perc Endo', 203143, 481, 68);
insert into products (id, name, description, price, stock, store_id) values (94, 'Appetizer - Spring Roll, Veg', 'Excision of Aortic Valve, Percutaneous Endoscopic Approach', 701870, 231, 32);
insert into products (id, name, description, price, stock, store_id) values (95, 'Black Currants', 'Beam Radiation of Mandible using Electrons, Intraoperative', 416479, 124, 38);
insert into products (id, name, description, price, stock, store_id) values (96, 'Wine - White, Pelee Island', 'Introduction of Nutritional into Mouth/Phar, Via Opening', 303103, 1, 86);
insert into products (id, name, description, price, stock, store_id) values (97, 'Lambcasing', 'Supplement R Up Lobe Bronc with Synth Sub, Open Approach', 193132, 497, 15);
insert into products (id, name, description, price, stock, store_id) values (98, 'Cake - Mini Potato Pancake', 'Insertion of Tissue Expander into Right Breast, Via Opening', 832276, 243, 90);
insert into products (id, name, description, price, stock, store_id) values (99, 'Guinea Fowl', 'Introduction of Nutritional Substance into Upper GI, Endo', 39619, 321, 40);
insert into products (id, name, description, price, stock, store_id) values (100, 'Sausage - Andouille', 'Reposition Jejunum, Open Approach', 441146, 378, 96);
insert into products (id, name, description, price, stock, store_id) values (101, 'Cape Capensis - Fillet', 'HDR Brachytherapy of Brain Stem using Palladium 103', 366948, 443, 35);
insert into products (id, name, description, price, stock, store_id) values (102, 'V8 - Vegetable Cocktail', 'Drainage of Right Shoulder Region, Perc Approach, Diagn', 359838, 280, 49);
insert into products (id, name, description, price, stock, store_id) values (103, 'Canada Dry', 'Destruction of Right Maxilla, Percutaneous Approach', 609761, 157, 92);
insert into products (id, name, description, price, stock, store_id) values (104, 'Soup - Campbells, Butternut', 'Revision of Drainage Device in L Knee Jt, Perc Endo Approach', 557414, 198, 52);
insert into products (id, name, description, price, stock, store_id) values (105, 'Shrimp - 100 / 200 Cold Water', 'Excision of Left Maxillary Sinus, Perc Approach, Diagn', 361871, 335, 64);
insert into products (id, name, description, price, stock, store_id) values (106, 'Duck - Whole', 'Insertion of Infusion Dev into Thor Aorta Asc, Perc Approach', 959967, 247, 24);
insert into products (id, name, description, price, stock, store_id) values (107, 'Veal - Loin', 'Revision of Infusion Device in C-thor Disc, Perc Approach', 264912, 284, 57);
insert into products (id, name, description, price, stock, store_id) values (108, 'Soup - Chicken And Wild Rice', 'Bypass Esophag to Jejunum w Nonaut Sub, Perc Endo', 215451, 369, 39);
insert into products (id, name, description, price, stock, store_id) values (109, 'Cheese - Roquefort Pappillon', 'Bypass R Ventricle to Pulm Trunk w Zooplastic, Perc Endo', 891684, 21, 88);
insert into products (id, name, description, price, stock, store_id) values (110, 'Beef - Tongue, Fresh', 'Release Right Internal Mammary Lymphatic, Perc Endo Approach', 613436, 131, 11);
insert into products (id, name, description, price, stock, store_id) values (111, 'Capon - Whole', 'Transfer R Low Arm Subcu/Fascia, Perc Approach', 957330, 382, 42);
insert into products (id, name, description, price, stock, store_id) values (112, 'External Supplier', 'Reposition Right Renal Artery, Percutaneous Approach', 735046, 143, 53);
insert into products (id, name, description, price, stock, store_id) values (113, 'Muskox - French Rack', 'MRI of Bi Up Extrem Art using Oth Contrast, Unenh, Enhance', 64640, 359, 21);
insert into products (id, name, description, price, stock, store_id) values (114, 'Pie Pecan', 'Transfuse Nonaut Platelets in Central Vein, Perc', 125833, 489, 45);
insert into products (id, name, description, price, stock, store_id) values (115, 'Squash - Pattypan, Yellow', 'Wound Management Treatment of Integu Body', 975419, 159, 10);
insert into products (id, name, description, price, stock, store_id) values (116, 'Radish', 'Drainage of R Hip Bursa/Lig, Open Approach, Diagn', 391279, 24, 67);
insert into products (id, name, description, price, stock, store_id) values (117, 'Glaze - Clear', 'Repair Left Kidney Pelvis, Open Approach', 236707, 98, 3);
insert into products (id, name, description, price, stock, store_id) values (118, 'Horseradish - Prepared', 'Drainage of Uterus, Endo', 367740, 182, 15);
insert into products (id, name, description, price, stock, store_id) values (119, 'Amaretto', 'Destruction of Left Upper Eyelid, Open Approach', 121996, 240, 80);
insert into products (id, name, description, price, stock, store_id) values (120, 'Cheese - Asiago', 'Bypass Duodenum to Duoden w Nonaut Sub, Perc Endo', 687162, 367, 92);
insert into products (id, name, description, price, stock, store_id) values (121, 'Sour Puss - Tangerine', 'Fusion >7 T Jt w Autol Sub, Post Appr A Col, Perc', 578808, 251, 27);
insert into products (id, name, description, price, stock, store_id) values (122, 'Wine - Barossa Valley Estate', 'Removal of Drainage Device from R Up Extrem, Perc Approach', 548281, 423, 2);
insert into products (id, name, description, price, stock, store_id) values (123, 'Nut - Walnut, Pieces', 'Release Right Metacarpophalangeal Joint, External Approach', 437095, 401, 23);
insert into products (id, name, description, price, stock, store_id) values (124, 'Soup - Campbells Broccoli', 'Drainage of Left Buttock, Percutaneous Approach, Diagnostic', 648448, 274, 34);
insert into products (id, name, description, price, stock, store_id) values (125, 'Papayas', 'Motor Functn Treatment of Integu Low Back/LE using Orthosis', 164516, 167, 23);
insert into products (id, name, description, price, stock, store_id) values (126, 'Vaccum Bag 10x13', 'Fragmentation in Ileum, Percutaneous Endoscopic Approach', 681231, 174, 62);
insert into products (id, name, description, price, stock, store_id) values (127, 'Pizza Pizza Dough', 'Supplement R Kidney Pelvis w Nonaut Sub, Perc Endo', 865930, 194, 49);
insert into products (id, name, description, price, stock, store_id) values (128, 'Beef - Striploin Aa', 'Reposition Left Knee Joint, Percutaneous Endoscopic Approach', 792626, 458, 90);
insert into products (id, name, description, price, stock, store_id) values (129, 'Trout - Smoked', 'Bypass L Subclav Vein to Up Vein w Autol Art, Open', 791996, 89, 1);
insert into products (id, name, description, price, stock, store_id) values (130, 'Dome Lid Clear P92008h', 'Excision of Portal Vein, Percutaneous Approach', 215434, 426, 34);
insert into products (id, name, description, price, stock, store_id) values (131, 'Vacuum Bags 12x16', 'Revision of Nonaut Sub in Diaphragm, Via Opening', 647962, 491, 99);
insert into products (id, name, description, price, stock, store_id) values (132, 'Duck - Fat', 'Fragmentation in Right Parotid Duct, Via Opening', 961064, 440, 33);
insert into products (id, name, description, price, stock, store_id) values (133, 'Chicken - Tenderloin', 'LDR Brachytherapy of Pelvic Region using Cesium 137', 981377, 456, 79);
insert into products (id, name, description, price, stock, store_id) values (134, 'Filter - Coffee', 'Beam Radiation of Chest Wall using Neutrons', 993025, 342, 26);
insert into products (id, name, description, price, stock, store_id) values (135, 'Cilantro / Coriander - Fresh', 'Reposition R Femur Shaft w Monopln Ext Fix, Perc Endo', 938147, 271, 95);
insert into products (id, name, description, price, stock, store_id) values (136, 'Goat - Leg', 'Replace of L Innom Vein with Synth Sub, Perc Endo Approach', 388555, 131, 29);
insert into products (id, name, description, price, stock, store_id) values (137, 'Wine - Ice Wine', 'Upper Veins, Excision', 10472, 136, 38);
insert into products (id, name, description, price, stock, store_id) values (138, 'Nantucket - 518ml', 'Drainage of Celiac Artery, Open Approach, Diagnostic', 212237, 266, 76);
insert into products (id, name, description, price, stock, store_id) values (139, 'Ice Cream Bar - Oreo Cone', 'Excision of Right Lower Lung Lobe, Via Opening', 315933, 340, 33);
insert into products (id, name, description, price, stock, store_id) values (140, 'Cheese - Bocconcini', 'Dilate L Int Carotid, Bifurc, w 3 Intralum Dev, Perc Endo', 395972, 353, 48);
insert into products (id, name, description, price, stock, store_id) values (141, 'Ice Cream - Super Sandwich', 'Extirpation of Matter from R Popl Art, Open Approach', 950398, 228, 58);
insert into products (id, name, description, price, stock, store_id) values (142, 'Milk - Chocolate 500ml', 'Bypass R Com Iliac Art to B Femor A w Nonaut Sub, Open', 862760, 214, 98);
insert into products (id, name, description, price, stock, store_id) values (143, 'Beef Tenderloin Aaa', 'Removal of Drain Dev from Thyroid Gland, Extern Approach', 104025, 136, 5);
insert into products (id, name, description, price, stock, store_id) values (144, 'Scallops - 10/20', 'Removal of Nonaut Sub from L Humeral Head, Perc Approach', 146621, 96, 80);
insert into products (id, name, description, price, stock, store_id) values (145, 'Pasta - Gnocchi, Potato', 'Exercise Trmt Musculosk Head, Neck w Mech/Electromech Equip', 462203, 73, 100);
insert into products (id, name, description, price, stock, store_id) values (146, 'Glycerine', 'Excision of Right Lower Lung Lobe, Open Approach', 367142, 493, 43);
insert into products (id, name, description, price, stock, store_id) values (147, 'Plasticknivesblack', 'Revise Nonaut Sub in Low Extrem Subcu/Fascia, Perc', 693795, 77, 72);
insert into products (id, name, description, price, stock, store_id) values (148, 'Corn - Cream, Canned', 'Drainage of Colic Vein, Percutaneous Endoscopic Approach', 665161, 386, 78);
insert into products (id, name, description, price, stock, store_id) values (149, 'Cheese - Cheddar, Mild', 'CT Scan of Bi Eye using Oth Contrast, Unenh, Enhance', 507758, 348, 16);
insert into products (id, name, description, price, stock, store_id) values (150, 'Wine - Chateau Timberlay', 'Reposition Right Sacroiliac Joint, Percutaneous Approach', 637322, 344, 33);
insert into products (id, name, description, price, stock, store_id) values (151, 'Pineapple - Regular', 'Revision of Autol Sub in Mouth/Throat, Extern Approach', 734873, 393, 68);
insert into products (id, name, description, price, stock, store_id) values (152, 'Chicken Breast Wing On', 'Release Left Internal Mammary Lymphatic, Open Approach', 444704, 182, 7);
insert into products (id, name, description, price, stock, store_id) values (153, 'Langers - Mango Nectar', 'Transfer R Low Leg Muscle with Subcu, Perc Endo Approach', 100782, 60, 2);
insert into products (id, name, description, price, stock, store_id) values (154, 'Cranberries - Frozen', 'Ear, Nose, Sinus, Destruction', 936510, 369, 6);
insert into products (id, name, description, price, stock, store_id) values (155, 'Grouper - Fresh', 'Occlusion R Up Extrem Lymph w Intralum Dev, Perc', 546345, 492, 59);
insert into products (id, name, description, price, stock, store_id) values (156, 'Sea Bass - Fillets', 'Destruction of Right Lower Leg Tendon, Percutaneous Approach', 928157, 204, 76);
insert into products (id, name, description, price, stock, store_id) values (157, 'Browning Caramel Glace', 'HDR Brachytherapy of Tongue using Cesium 137', 816510, 482, 34);
insert into products (id, name, description, price, stock, store_id) values (158, 'Flower - Carnations', 'Release Right Orbit, Percutaneous Endoscopic Approach', 325943, 305, 20);
insert into products (id, name, description, price, stock, store_id) values (159, 'Bread - Flat Bread', 'Removal of Nonaut Sub from Cerv Jt, Perc Endo Approach', 274067, 472, 98);
insert into products (id, name, description, price, stock, store_id) values (160, 'Buttons', 'Reposition Right Shoulder Joint, Perc Endo Approach', 63291, 292, 10);
insert into products (id, name, description, price, stock, store_id) values (161, 'Wine - Masi Valpolocell', 'Dilate L Thyroid Art, Bifurc, w 3 Drug-elut, Perc', 528104, 285, 95);
insert into products (id, name, description, price, stock, store_id) values (162, 'Chocolate Eclairs', 'Bypass R Popl Art to Low Ex Art w Autol Art, Open', 891004, 164, 24);
insert into products (id, name, description, price, stock, store_id) values (163, 'Emulsifier', 'Fluoroscopy of Lumbosacral Joint using High Osmolar Contrast', 294834, 376, 17);
insert into products (id, name, description, price, stock, store_id) values (164, 'Wine - Hardys Bankside Shiraz', 'Dilation of L Post Tib Art with 2 Drug-elut, Open Approach', 877900, 256, 47);
insert into products (id, name, description, price, stock, store_id) values (165, 'Mushroom - Porcini Frozen', 'Excision of Upper Esophagus, Endo', 535033, 354, 55);
insert into products (id, name, description, price, stock, store_id) values (166, 'Cake - Sheet Strawberry', 'Revision of Monitoring Device in Pancreat Duct, Via Opening', 166983, 167, 16);
insert into products (id, name, description, price, stock, store_id) values (167, 'Tabasco Sauce, 2 Oz', 'Bypass Innom Art to L Low Arm Art w Autol Vn, Open', 902191, 299, 52);
insert into products (id, name, description, price, stock, store_id) values (168, 'Ocean Spray - Kiwi Strawberry', 'Revision of Autol Sub in Cranial Nrv, Perc Endo Approach', 337289, 446, 83);
insert into products (id, name, description, price, stock, store_id) values (169, 'Parsley - Fresh', 'Excision of Left Common Iliac Vein, Open Approach, Diagn', 795892, 183, 99);
insert into products (id, name, description, price, stock, store_id) values (170, 'Tomato - Tricolor Cherry', 'Supplement L Up Arm Tendon w Nonaut Sub, Perc Endo', 273331, 411, 81);
insert into products (id, name, description, price, stock, store_id) values (171, 'Paste - Black Olive', 'Removal of Drainage Device from L Tarsal Jt, Perc Approach', 948315, 342, 77);
insert into products (id, name, description, price, stock, store_id) values (172, 'Garam Marsala', 'Alteration of Right Axilla with Nonaut Sub, Perc Approach', 734203, 348, 94);
insert into products (id, name, description, price, stock, store_id) values (173, 'Ecolab - Medallion', 'Restriction of L Colic Art with Intralum Dev, Open Approach', 198225, 452, 42);
insert into products (id, name, description, price, stock, store_id) values (174, 'Cake Circle, Foil, Scallop', 'Repair Left Thorax Bursa and Ligament, Perc Endo Approach', 36891, 150, 57);
insert into products (id, name, description, price, stock, store_id) values (175, 'Appetizer - Mushroom Tart', 'Detachment at Left Foot, Partial 2nd Ray, Open Approach', 832540, 313, 30);
insert into products (id, name, description, price, stock, store_id) values (176, 'Kellogs All Bran Bars', 'Drainage of Epidural Space with Drain Dev, Perc Approach', 184177, 250, 22);
insert into products (id, name, description, price, stock, store_id) values (177, 'Tequila Rose Cream Liquor', 'Release Right Middle Ear, Open Approach', 999042, 309, 66);
insert into products (id, name, description, price, stock, store_id) values (178, 'Caviar - Salmon', 'Revision of Synthetic Substitute in Omentum, Perc Approach', 526730, 157, 53);
insert into products (id, name, description, price, stock, store_id) values (179, 'Wine - Crozes Hermitage E.', 'Dilation of Lingula Bronchus, Endo', 737274, 282, 56);
insert into products (id, name, description, price, stock, store_id) values (180, 'Mangoes', 'Supplement R Temporal Art with Autol Sub, Open Approach', 241432, 389, 54);
insert into products (id, name, description, price, stock, store_id) values (181, 'Wine - Dubouef Macon - Villages', 'Dilation of Right Kidney Pelvis, Percutaneous Approach', 923702, 451, 17);
insert into products (id, name, description, price, stock, store_id) values (182, 'Beef - Ox Tail, Frozen', 'Dilate Low Art, Bifurc, w 2 Intralum Dev, Open', 409371, 359, 61);
insert into products (id, name, description, price, stock, store_id) values (183, 'Onions - Cippolini', 'Insert Infusion Dev in R Verteb Vein, Perc Endo', 151101, 39, 28);
insert into products (id, name, description, price, stock, store_id) values (184, 'Muffin - Carrot Individual Wrap', 'Removal of Radioactive Element from Left Lung, Open Approach', 79035, 98, 55);
insert into products (id, name, description, price, stock, store_id) values (185, 'Swordfish Loin Portions', 'Excision of Left Buttock, Percutaneous Approach, Diagnostic', 215633, 418, 83);
insert into products (id, name, description, price, stock, store_id) values (186, 'Tequila Rose Cream Liquor', 'Supplement Abdominal Wall with Autol Sub, Open Approach', 404970, 134, 63);
insert into products (id, name, description, price, stock, store_id) values (187, 'Buffalo - Short Rib Fresh', 'Occlusion L Axilla Vein w Intralum Dev, Perc Endo', 878643, 88, 42);
insert into products (id, name, description, price, stock, store_id) values (188, 'Sambuca Cream', 'Release R Low Extrem Bursa/Lig, Open Approach', 803347, 49, 77);
insert into products (id, name, description, price, stock, store_id) values (189, 'Corn - Mini', 'Occlusion of Left Cephalic Vein, Percutaneous Approach', 139104, 470, 57);
insert into products (id, name, description, price, stock, store_id) values (190, 'Brandy Cherry - Mcguinness', 'Drainage of Left Basilic Vein, Open Approach, Diagnostic', 205522, 167, 98);
insert into products (id, name, description, price, stock, store_id) values (191, 'Rhubarb', 'Bypass Inf Vena Cava to Inf Mesent V w Synth Sub, Perc Endo', 456764, 92, 25);
insert into products (id, name, description, price, stock, store_id) values (192, 'Juice - Cranberry, 341 Ml', 'Bypass Right Ventricle to Thoracic Artery, Open Approach', 516942, 184, 87);
insert into products (id, name, description, price, stock, store_id) values (193, 'Carbonated Water - Wildberry', 'Extraction of Left Wrist Bursa and Ligament, Open Approach', 699531, 407, 92);
insert into products (id, name, description, price, stock, store_id) values (194, 'Table Cloth 62x120 White', 'Supplement R Tunica Vaginalis with Synth Sub, Open Approach', 173663, 191, 10);
insert into products (id, name, description, price, stock, store_id) values (195, 'Plasticspoonblack', 'Removal of Drainage Device from Ureter, Via Opening', 562202, 228, 25);
insert into products (id, name, description, price, stock, store_id) values (196, 'Garlic Powder', 'Release Vestibular Gland, Open Approach', 852734, 339, 1);
insert into products (id, name, description, price, stock, store_id) values (197, 'Tray - Foam, Square 4 - S', 'Removal of Intralum Dev from Thoracic Duct, Perc Approach', 888308, 315, 38);
insert into products (id, name, description, price, stock, store_id) values (198, 'Island Oasis - Sweet And Sour Mix', 'Reposition L Metatarsophal Jt with Ext Fix, Open Approach', 28631, 13, 12);
insert into products (id, name, description, price, stock, store_id) values (199, 'Icecream - Dstk Super Cone', 'Dilate L Radial Art, Bifurc, w 3 Drug-elut, Perc', 958292, 2, 16);
insert into products (id, name, description, price, stock, store_id) values (200, 'Wine - Redchard Merritt', 'Detachment at Right Middle Finger, Low, Open Approach', 92759, 306, 15);
